### PR TITLE
[REEF-918] Remove deprecated functions in ClrHandlerHelper

### PR DESCRIPTION
**Pull request by afchung**
JIRA:
  [REEF-918] https://issues.apache.org/jira/browse/REEF-918

Pull Request:
  Closes #

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Hi, @afchung . 
Could you rebase this PR to the master?

Of course, the Jenkins error is irrelevant to that. :)

**Comment by afchung** [comment]
@dongjoon-hyun  Rebased. Thanks!

**Comment by dongjoon-hyun** [comment]
It is merged to the master. 
Sorry for delay, @afchung .

**Comment by afchung** [comment]
@dongjoon-hyun no problem! Thanks for the merge!

**Pull request closed without merging**
