### PR TITLE
[REEF-1401] Fix Driver Restart to correctly use the right folder

### PR DESCRIPTION
**Pull request by afchung**
This addressed the issue by
  * Using JobSubmissionDirectory instead of DriverJobSubmissionDirectory in DFSEvaluatorPreserver.
  * Logging in HandleException.

JIRA:
  [REEF-1401](https://issues.apache.org/jira/browse/REEF-1401)

### CODE REVIEW

**Comment by markusweimer** [comment]
Should `DriverJobSubmissionDirectory` be deprecated then? If so, we should use its documentation for `JobSubmissionDirectory`, as it is much better :)

**Comment by afchung** [comment]
@markusweimer agreed. Created REEF-1402.

**Comment by afchung** [comment]
Tested on HDInsight.

**Comment by markusweimer** [comment]
LGTM. Will merge.

**Pull request closed without merging**
