### PR TITLE
[REEF-1858] Remove `oraclejdk7` builds on Travis.

### PR DESCRIPTION
**Pull request by markusweimer**
JIRA:
  [REEF-1858](https://issues.apache.org/jira/browse/REEF-1858)

### CODE REVIEW

**Comment by tcNickolas** [comment]
Interestingly, two other jobs both fail in Travis, one with finbugs and one with some system error. But removal of `oraclejdk7` job is probably not the cause of these failures

**Comment by markusweimer** [comment]
> Interestingly, two other jobs both fail in Travis, one with finbugs and one with some system error. 

Yes, this is curious. I wanted to try another approach next, where we target the "old" Ubuntu release and keep `oraclejdk7` in the mix. WDYT of this approach?

**Comment by tcNickolas** [comment]
If we want to guarantee that REEF keeps running on Oracle Java 7, then it's better to try and keep `oraclejdk7` of course. Also, it will give us more statistics on transient test failures on Java side (which are fewer than on .NET side but still not non-existent).

**Comment by markusweimer** [comment]
OK, I made a push trying that.

**Comment by markusweimer** [comment]
This seems to have worked. @tcNickolas, shall we go with this solution?

**Comment by markusweimer** [comment]
@tcNickolas are you OK with me merging it? We are seasonly low on committers right now (everyone is out on vacation :) )

**Comment by tcNickolas** [comment]
Yes, of course.

**Pull request closed without merging**
