### PR TITLE
[REEF-976] Fix broken C# Tests caused by race condition of local RM

### PR DESCRIPTION
**Pull request by afchung**
This addressed the issue by
  * Having Driver ACK a DONE Evaluator.

JIRA:
  [REEF-976](https://issues.apache.org/jira/browse/REEF-976)

### CODE REVIEW

**Comment by markusweimer** [comment]
Shouldn't the Java code also be updated to wait for the ACK?

**Comment by markusweimer** [comment]
I tested this. The tests get stuck and the following tests never get executed:

```
Test Name:	Org.Apache.REEF.Wake.Tests.StreamingRemoteManagerTest.TestStreamingCommunicationThreeNodesBothWays
Test FullName:	Org.Apache.REEF.Wake.Tests.StreamingRemoteManagerTest.TestStreamingCommunicationThreeNodesBothWays
Test Source:	C:\src\reef\lang\cs\Org.Apache.REEF.Wake.Tests\StreamingRemoteManagerTest.cs : line 166
Test Outcome:	Not Run
Test Duration:	0:00:00
```

And:

```
Test Name:	Org.Apache.REEF.Wake.Tests.StreamingRemoteManagerTest.TestStreamingCommunicationThreeNodesOneWay
Test FullName:	Org.Apache.REEF.Wake.Tests.StreamingRemoteManagerTest.TestStreamingCommunicationThreeNodesOneWay
Test Source:	C:\src\reef\lang\cs\Org.Apache.REEF.Wake.Tests\StreamingRemoteManagerTest.cs : line 127
Test Outcome:	Not Run
Test Duration:	0:00:00
```

And:

```
Test Name:	Org.Apache.REEF.Wake.Tests.StreamingRemoteManagerTest.TestStreamingOneWayCommunication
Test FullName:	Org.Apache.REEF.Wake.Tests.StreamingRemoteManagerTest.TestStreamingOneWayCommunication
Test Source:	C:\src\reef\lang\cs\Org.Apache.REEF.Wake.Tests\StreamingRemoteManagerTest.cs : line 42
Test Outcome:	Not Run
Test Duration:	0:00:00
```

And:

```
Test Name:	Org.Apache.REEF.Wake.Tests.StreamingRemoteManagerTest.TestStreamingRegisterObserverByType
Test FullName:	Org.Apache.REEF.Wake.Tests.StreamingRemoteManagerTest.TestStreamingRegisterObserverByType
Test Source:	C:\src\reef\lang\cs\Org.Apache.REEF.Wake.Tests\StreamingRemoteManagerTest.cs : line 281
Test Outcome:	Not Run
Test Duration:	0:00:00
```

And:

```
Test Name:	Org.Apache.REEF.Wake.Tests.StreamingRemoteManagerTest.TestStreamingRemoteSenderCallback
Test FullName:	Org.Apache.REEF.Wake.Tests.StreamingRemoteManagerTest.TestStreamingRemoteSenderCallback
Test Source:	C:\src\reef\lang\cs\Org.Apache.REEF.Wake.Tests\StreamingRemoteManagerTest.cs : line 235
Test Outcome:	Not Run
Test Duration:	0:00:00
```

**Comment by afchung** [comment]
@markusweimer which tests get stuck? I don't see it on my end.

**Comment by afchung** [comment]
The AppVeyor build is also passing, but only failed due to running for more than 60 minutes on all the tests.

**Comment by tcNickolas** [comment]
AppVeyor build is always failing due to `StreamingRemoteManagerTest` being stuck, you can't say it's passing, you can only say it's failing if it's failing some other tests :-)

**Comment by afchung** [comment]
@tcNickolas Ah, I was under the impression that the broadcast reduce tests were failing on Appveyor. Sorry!

**Comment by afchung** [comment]
@tcNickolas could you try running the tests for this PR as well if you have time?

**Comment by markusweimer** [comment]
I ran again on a machine with 6 cores, and the tests all run. However, one fails:

```
Test Name:	Org.Apache.REEF.Tests.Utility.TestDriverConfigGenerator.TestGeneratingDriverConfigFileWithoutNameServer
Test FullName:	Org.Apache.REEF.Tests.Utility.TestDriverConfigGenerator.TestGeneratingDriverConfigFileWithoutNameServer
Test Source:	D:\src\reef\lang\cs\Org.Apache.REEF.Tests\Utility\TestDriverConfigGenerator.cs : line 76
Test Outcome:	Failed
Test Duration:	0:00:00.11

Result StackTrace:	
at Org.Apache.REEF.Driver.Bridge.ClrClientHelper.ExtractConfigfileFromJar(String reefJar, IList`1 configFiles, String dropFolder) in D:\src\reef\lang\cs\Org.Apache.REEF.Driver\Bridge\ClrClientHelper.cs:line 60
   at Org.Apache.REEF.Driver.DriverConfigGenerator.ExtractConfigFromJar(String jarfileFolder) in D:\src\reef\lang\cs\Org.Apache.REEF.Driver\DriverConfigGenerator.cs:line 154
   at Org.Apache.REEF.Driver.DriverConfigGenerator.DriverConfigurationBuilder(DriverConfigurationSettings driverConfigurationSettings) in D:\src\reef\lang\cs\Org.Apache.REEF.Driver\DriverConfigGenerator.cs:line 51
   at Org.Apache.REEF.Tests.Utility.TestDriverConfigGenerator.TestGeneratingDriverConfigFileWithoutNameServer() in D:\src\reef\lang\cs\Org.Apache.REEF.Tests\Utility\TestDriverConfigGenerator.cs:line 88
Result Message:	
System.InvalidOperationException : Failed to extract files from jar file with stdout :and stderr:java.lang.IllegalArgumentException: MALFORMED
	at java.util.zip.ZipCoder.toString(ZipCoder.java:58)
	at java.util.zip.ZipFile.getZipEntry(ZipFile.java:567)
	at java.util.zip.ZipFile.access$900(ZipFile.java:61)
	at java.util.zip.ZipFile$ZipEntryIterator.next(ZipFile.java:525)
	at java.util.zip.ZipFile$ZipEntryIterator.nextElement(ZipFile.java:500)
	at java.util.zip.ZipFile$ZipEntryIterator.nextElement(ZipFile.java:481)
	at sun.tools.jar.Main.extract(Main.java:1008)
	at sun.tools.jar.Main.run(Main.java:305)
	at sun.tools.jar.Main.main(Main.java:1288)
```

**Comment by tcNickolas** [comment]
@markusweimer I think you're switching machines between test runs and that invalidates the results. Do all reports of `StreamingRemoteManagerTest` tests not executed from this PR and other ones come from the same machine, or from different ones?

**Comment by markusweimer** [comment]
> Do all reports of `StreamingRemoteManagerTest` tests not executed from this PR and other ones come from the same machine, or from different ones?

Yes. It is a i7 based ultrabook with 2 cores with hyperthreading. The last test, where TestGeneratingDriverConfigFileWithoutNameServer` failed  was run on a 6 Core i7 with hyper threading. I can make that test pass if I run it in isolation, though.

**Comment by tcNickolas** [comment]
Maybe each of us should create a kind of personal "baseline" for our .NET tests? They are all machine-dependent, so if one runs tests on master branch on one machine 10 times (from scratch each time - I know I'm asking a lot), they'll know which tests fail on that specific machine, and then when they test a PR, they can have higher levels of certainty that this PR didn't introduce new failures, just the ones specific to this machine? Otherwise, you switch machines, you switch failures, and it's very hard to distinguish ones which are caused by a PR from ones which are caused by a machine.

I know this is AppVeyor's job, and a human shouldn't do it. But with these tests being always stuck there we can't get a good picture from it yet.

And then in an ideal world we'd need to troubleshoot each failure and fix it...

**Comment by markusweimer** [comment]
> And then in an ideal world we'd need to troubleshoot each failure and fix it...

I think that is the right way forward. I am actually OK merging this PR. It fixes *one* issue. The fact that we have others shouldn't stop us.

**Comment by afchung** [comment]
@markusweimer @tcNickolas what is the status of this PR? Is there anything else I should fix?

**Comment by markusweimer** [comment]
Yes, please add the same code to the Java side or file a JIRA such that we do this at a later time.

Other than that, this seems to solve an issue, and doesn't make other tests not pass that pass reliably in `master`.

**Comment by afchung** [comment]
@markusweimer created [REEF-1310](https://issues.apache.org/jira/browse/REEF-1310).

**Comment by markusweimer** [comment]
LGTM now

@tcNickolas Are you OK with merging this in the name of partial progress?

**Comment by tcNickolas** [comment]
I have no objections to merging. Of course we can't fix everything in one PR :-)

**Comment by markusweimer** [comment]
OK. Will merge.

**Comment by markusweimer** [comment]
I merged this. Not sure why the PR isn't closed yet.

**Pull request closed without merging**
