### PR TITLE
[REEF-1381] Allow to add Observer for ActiveContextManager

### PR DESCRIPTION
**Pull request by jwang98052**
* Allow to add an observer for ActiveContextManager
* Notify the observer when all contexts are received
* Added test cases for it

JIRA: [REEF-1381](https://issues.apache.org/jira/browse/REEF-1381)
This closes

### CODE REVIEW

**Comment by tcNickolas** [comment]
I'll take a look

**Comment by tcNickolas** [comment]
The tests verify that if `OnNext(ActiveContextManager)` is called, it has correct values, but it doesn't verify that it actually gets called. We can add a global flag which `OnNext` would update when called, and test would check that the flag is set.

**Comment by tcNickolas** [comment]
I've done a pass

**Comment by dkm2110** [comment]
@jwang98052  I had a look..Just one higher level comment or question: Should we subscribe IObserver{ActiveCOntextManager}

**Comment by jwang98052** [comment]
@tcNickolas I have addressed your comments.

**Comment by tcNickolas** [comment]
LGTM. I can merge after @dkm2110 signs off

**Comment by jwang98052** [comment]
@dkm2110 I have changed it in the previous commit. Please have a look.

**Comment by dkm2110** [comment]
LGTM

**Comment by tcNickolas** [comment]
.NET tests pass locally, so I'll merge without waiting for AppVeyor approval

**Pull request closed without merging**
