### PR TITLE
[REEF-1217] Update version to 0.15.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by yunseong**
This addressed the issue by
  * Updating the version to 0.15-SNAPSHOT
  * Command (OSX zsh): python $REEF_PATH/dev/change_version.py -s true $REEF_PATH 0.15.0

JIRA:
  [REEF-1217](https://issues.apache.org/jira/browse/REEF-1217)

Pull Request:
  Closes

### CODE REVIEW

**Comment by dafrista** [comment]
I'll take a look.

**Comment by yunseong** [comment]
Could anyone take a look if you have time? Thanks!

**Comment by yunseong** [comment]
Ah, thanks @dafrista!!

**Comment by dafrista** [comment]
+1 on Java side. It looks like maven installs the correct 0.15.0-SNAPSHOT packages.
Can someone check on the windows side that packages build smoothly as 0.15.0-SNAPSHOT? Possibly @markusweimer ? :)

**Comment by markusweimer** [comment]
Will test to build this on Windows, both java and .NET

**Comment by markusweimer** [comment]
The java side seems to be fine, but the .NET side has a failure in `TestDeserializationForContextAndTask`:

```
System.IO.FileLoadExceptionCould not load file or assembly 'Org.Apache.REEF.Driver, Version=0.14.0.0, Culture=neutral, PublicKeyToken=c27bf5b2e9a7ddb9' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
```

@jwang98052, this is the test that relies on a magic artifact in the repository, right? Can you explain how to recreate it such that we can add that to the version upgrade script. Or, better yet, delete the test and replace it with one without this problem.

**Comment by dongjoon-hyun** [comment]
Hi, I think we need to upgrade the script. The problem comes here, `lang\cs\Org.Apache.REEF.Examples\ConfigFiles\evaluator.conf`.
As you see, the version and public key is hard-coded.
```
Objavro.schema~~~
  "Bindings": [
    {
      "key": "Org.Apache.REEF.Common.Tasks.ITask, Org.Apache.REEF.Common, Version=0.14.0.0, Culture=neutral, PublicKeyToken=c27bf5b2e9a7ddb9",
      "value": "Org.Apache.REEF.Examples.HelloREEF.HelloTask, Org.Apache.REEF.Examples.HelloREEF, Version=0.14.0.0, Culture=neutral, PublicKeyToken=c27bf5b2e9a7ddb9"
    },
    {
      "key": "Org.Apache.REEF.Common.Tasks.TaskConfigurationOptions+Identifier, Org.Apache.REEF.Common, Version=0.14.0.0, Culture=neutral, PublicKeyToken=c27bf5b2e9a7ddb9",
      "value": "HelloTask"
    }
  ]
} org.apache.reef.runtime.common.evaluator.parameters.RootContextConfiguration {
  "language": "Cs",
  "Bindings": [
    {
      "key": "Org.Apache.REEF.Driver.Context.ContextConfigurationOptions+ContextIdentifier, Org.Apache.REEF.Driver, Version=0.14.0.0, Culture=neutral, PublicKeyToken=c27bf5b2e9a7ddb9",
      "value": "RootContext_Node-2-1447450298921"
    }
  ]
}
```

**Comment by dongjoon-hyun** [comment]
I think we can edit that file with python Avro library. But, we need `PublicKeyToken` as a new argument for that script. Any idea?

**Comment by dongjoon-hyun** [comment]
Hi, All.
I created a JIRA issue [REEF-1220](https://issues.apache.org/jira/browse/REEF-1220) and PR #857 to update `change_version.py` to handle Avro-binary format resource files: `evaluator.conf` and `evaluatorWithService.conf`.
After applying #857 and executing `C:\Python27\python.exe .\dev\change_version.py -s true C:\Users\dongjoon\reef 0.15.0`, all tests in `Test Explorer` are passed.

Hopefully, I think this PR #857 would help @yunseong finishing the release.

**Comment by yunseong** [comment]
@dongjoon-hyun Thanks a lot for the help! I hope your work can fix the problem, but I'm not available right now. Could someone test & review #857? I'll do it if has not been done tonight.

**Comment by yunseong** [comment]
I've tried to test this PR on my end, but I installed 32bit Win10 where I'm not allowed to run tests for x64 architecture. I'll retry with 64-bit Windows, but it'd be appreciated if someone run test if you have time.

**Comment by yunseong** [comment]
As #860 has been merged, the tests should pass for this PR as well. @markusweimer Could you kindly test it once again when you have time? Thanks!

**Comment by markusweimer** [comment]
Will do.

**Comment by markusweimer** [comment]
.NET tests pass, will merge.

**Comment by yunseong** [comment]
Thanks @markusweimer! I also would like to thank @dongjoon-hyun and @jwang98052 for the help.

**Pull request closed without merging**
