### PR TITLE
[REEF-1786] Remove use of `Exceptions` class in O.A.R.Common

### PR DESCRIPTION
**Pull request by markusweimer**
JIRA:[REEF-1786](https://issues.apache.org/jira/browse/REEF-1786)

### CODE REVIEW

**Comment by markusweimer** [comment]
Dear reviewer, please pay attention to the cases where I replaced calls to `Exceptions.Caught` and `Exceptions.CaughtAndThrow`, as those looked like code smells to me while editing. Maybe we want to file issues for them as part of this review.

**Comment by tcNickolas** [comment]
AppVeyor failure seems to be caused by this change, both builds fail on the same test which is not one of our transiently failing ones:

    Org.Apache.REEF.Tests.Functional.Bridge.TestCloseTask.TestTaskWithNoCloseHandlerOnLocalRuntime

    Message "ExceptionCaught TaskCloseHandlerNotBoundException" expected to occur, but did not.
    Expected: True
    Actual:   False

    Error stack trace:

       at Org.Apache.REEF.Tests.Functional.ReefFunctionalTest.ValidateMessageSuccessfullyLogged(IEnumerable`1 messages, String subfolder, String fileName, String testFolder, Int32 numberOfOccurrences) in C:\projects\reef\lang\cs\Org.Apache.REEF.Tests\Functional\ReefFunctionalTest.cs:line 244
       at Org.Apache.REEF.Tests.Functional.Bridge.TestCloseTask.TestTaskWithNoCloseHandlerOnLocalRuntime() in C:\projects\reef\lang\cs\Org.Apache.REEF.Tests\Functional\Bridge\TestCloseTask.cs:line 107

**Comment by markusweimer** [comment]
Thanks, @tcNickolas, I am looking into that now.

**Comment by jwang98052** [comment]
LGTM except
1. fix test issue that is to look for some message
2. Can we merge other .Net related PL such as (REEF-1735) before this change to avoid merge conflict? As this change is more mechanical change and cross more classes.

**Comment by markusweimer** [comment]
I've decided to abandon this change in favor of one that *only* removes `Exceptions.throws` calls. The removal of the logging has too much potential to disrupt our current test infrastructure.

**Pull request closed without merging**
