### PR TITLE
[REEF-986] Switch all InterOp calls to call public get methods in Jav…

### PR DESCRIPTION
**Pull request by afchung**
…a instead of referencing private fields

JIRA:
  [REEF-986](https://issues.apache.org/jira/browse/REEF-986)

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Could you rebase this and resolve the conflicts?

**Comment by afchung** [comment]
@dongjoon-hyun Sure, I'll update the PR and rebase.

**Comment by afchung** [comment]
@dongjoon-hyun Updated. Please have another look. Thanks!

**Comment by dongjoon-hyun** [comment]
Thank you, @afchung . I will. 

By the way, as you know, Apache REEF GitHub is changed an hours ago. I'm not sure that it has no side effects.

**Comment by dongjoon-hyun** [comment]
It looks good to me and passes the tests. I'll merge this.

vstest.console.exe .\Org.Apache.REEF.Tests.dll /Platform:x64
```
Total tests: 16. Passed: 9. Failed: 0. Skipped: 7.
Test Run Successful.
Test execution time: 1.7728 Minutes
```

Test Explorer
```
========== Discover test finished: 62 found (0:00:03.0279929) ==========
...
========== Run test finished: 62 run (0:02:07.1093889) ==========
```

**Pull request closed without merging**
