### PR TITLE
[REEF-1860] Enable Mesos Node Labels

### PR DESCRIPTION
**Pull request by scan3**
This addressed the issue by
  * Enables REEF Runtime Mesos to use node labeling feature.

  Before running this test, configure Mesos to let the Mesos master
  sends offer with attribute "mylabel:mylabel" when resources are offered
  from a specific Mesos agent(node).

JIRA:
  [REEF-1860](https://issues.apache.org/jira/browse/REEF-1860)

Pull Request:
  This closes #

### CODE REVIEW

**Comment by bgchun** [comment]
@motus Once #1322 gets merged, @scan3 can update this PR to remove redundant code, I think. He's sending this PR to demonstrate his progress for his GSoC final evaluation, I think.

**Comment by DifferentSC** [comment]
Thanks for the comment, @motus and @bgchun! As @bgchun said, @scan3 is updating this PR for demonstrating his progress for the final report of GSoC. I agree that this PR could be cleaned up after #1322 gets merged.

**Comment by scan3** [comment]
@motus @bgchun @DifferentSC Thank you for the comment! As @bgchun and @DifferentSC said, I will clean up this PR after merging #1322.

**Comment by markusweimer** [comment]
@scan3 , can you please close this PR until #1322 is done?

**Comment by DifferentSC** [comment]
@markusweimer I will close this PR, as it is obvious that it should be merged after #1322 is done.

**Pull request closed without merging**
