### PR TITLE
[REEF-1120] Remove `incubator` in pom.xml

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
JIRA:
  [REEF-1120](https://issues.apache.org/jira/browse/REEF-1120)

Pull Request:
  This closes #

### CODE REVIEW

**Comment by tcNickolas** [comment]
Looks good, I'll merge

**Comment by tcNickolas** [comment]
Oops, I've forgotten to add PR # to commit message. Could you please close PR manually?

**Comment by dongjoon-hyun** [comment]
Sure. No problem. Ur, by the way, it seems to be merged and closed.

**Comment by dongjoon-hyun** [comment]
@tcNickolas , it looks much more natural and I think it's desirable behavior in GitHub.
Should we commit the specific PR number from now?

**Comment by tcNickolas** [comment]
We can discuss on dev list. Cons is, we don't have PR # in commit message anymore, so it takes one step longer to get to PR from commit (have to go via JIRA issue)

**Comment by dongjoon-hyun** [comment]
Oh, I forgot that cons. Then, let's keep the current way. I prefer direct access, too. Thank you for pointing out that.

**Pull request merged**
