### PR TITLE
[REEF-1045] Add exception handling in LocalScratchSpace

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
This PR implements two TODOs in `LocalScratchSpace.java`
by adding exception handling logic.

JIRA:
  [REEF-1045](https://issues.apache.org/jira/browse/REEF-1045)

Pull request:
  This closes #

### CODE REVIEW

**Comment by afchung** [comment]
Looks good to me, I'll test and merge.

**Comment by afchung** [comment]
I'm failing a test on Windows:
```
Running org.apache.reef.io.storage.SortingSpoolTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in org.apache.reef.io.storage.SortingSpoolTest
Running org.apache.reef.io.storage.SpoolFileTest
Tests run: 3, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.062 sec <<< FAILURE! - in org.apache.reef.io.storage.SpoolFileTest
testFile(org.apache.reef.io.storage.SpoolFileTest)  Time elapsed: 0.045 sec  <<< ERROR!
java.lang.RuntimeException: Fail to delete file:C:\Users\anchung\AppData\Local\Temp\reef-spoolTest-file3717652526155470889tmp
        at org.apache.reef.io.storage.local.LocalScratchSpace.delete(LocalScratchSpace.java:88)
        at org.apache.reef.io.storage.SpoolFileTest.testFile(SpoolFileTest.java:157)
```

I suspect it's because ``SerializerFileSpool`` doesn't close the ``OutputStream``. Could you have a look please? Thanks!

**Comment by dongjoon-hyun** [comment]
Oh, I will check that. Thank you.

**Comment by dongjoon-hyun** [comment]
Hi, @afchung . It's updated and rebased. For the `SerializerFileSpool`, `deleteOnExit` is used when `delete` fails.

**Comment by afchung** [comment]
Looks good, I'll test and merge.

**Comment by dongjoon-hyun** [comment]
Thank you, @afchung .

**Pull request closed without merging**
