### PR TITLE
[REEF-1463] Update Newtonsoft.Json to version 8.0.3

### PR DESCRIPTION
**Pull request by jwang98052**
JIRA: [REEF-1463](https://issues.apache.org/jira/browse/REEF-1463)
This closes

### CODE REVIEW

**Comment by tcNickolas** [comment]
I'll test

**Comment by tcNickolas** [comment]
The tests pass, but there are two more occurrences of 7.0 version in our sources left:

    lang/cs/Org.Apache.REEF.Evaluator.Tests/app.config
    lang/cs/Org.Apache.REEF.Examples.DriverRestart/App.config

Please fix them as well

**Comment by jwang98052** [comment]
@tcNickolas I have addressed the review comments.

**Comment by tcNickolas** [comment]
LGTM. This change passes tests and doesn't have any leftover 7.0.* versions. I'll merge

**Pull request closed without merging**
