### PR TITLE
[REEF-1088] Pass through O.A.R.Driver to hide unnecessarily public APIs

### PR DESCRIPTION
**Pull request by afchung**
JIRA:
  [REEF-1088](https://issues.apache.org/jira/browse/REEF-1088)

### CODE REVIEW

**Comment by markusweimer** [comment]
Looks good, I will merge

**Comment by tcNickolas** [comment]
Title says Driver, JIRA says Client

**Comment by markusweimer** [comment]
Thanks @tcNickolas I will fix this in the merge.

**Comment by afchung** [comment]
@tcNickolas @markusweimer Sorry about that!

**Pull request closed without merging**
