### PR TITLE
[REEF-1416] Add 0.15 to `Download & APIs` section on Apache REEF webpage

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
JIRA:
  [REEF-1416](https://issues.apache.org/jira/browse/REEF-1416)

Pull request:
  This closes #

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Hi, @tcNickolas .
Could you review this PR as the creator of `dev/update_website.py`? :)

**Comment by dongjoon-hyun** [comment]
Oh, AppVoyeyor job is queued for 12 hours. Interesting.

**Comment by dongjoon-hyun** [comment]
Hi, @markusweimer .
Could you review and merge this PR?

**Comment by tcNickolas** [comment]
I'll review this tomorrow, didn't have a chance today.
For AppVeyor check, it gets stuck more and more often recently, so we should use `[ci skip]` in commit messages whenever the PR doesn't touch actual REEF code to reduce the load on CI

**Comment by dongjoon-hyun** [comment]
Thank you! :)

**Pull request closed without merging**
