### PR TITLE
[REEF-1567] Update Newtonsoft Json.NET to version 9.0.1

### PR DESCRIPTION
**Pull request by inchiosa**
This addressed the issue by
- Changing references to Newtonsoft.Json 8.0.0.0 to 9.0.0.0
- Changing references to Newtonsoft.Json 8.0.3 to 9.0.1

JIRA:
 [REEF-1567](https://issues.apache.org/jira/browse/REEF-1567)

### CODE REVIEW

**Comment by tcNickolas** [comment]
Please resolve the conflicts this branch has with current master

**Comment by inchiosa** [comment]
I resolved the conflict

**Comment by jwang98052** [comment]
Let me package the change for our client to do a testing before merging.

**Comment by jwang98052** [comment]
I tried to use this PR to our application's code base and got some conflict. Looks like more coordination is required to have everyone move to the same version to avoid out of sync. For now, please don't merge this PR yet.

**Comment by markusweimer** [comment]
Where are we with this? Shall we postpone this change till after 0.16 is out?

**Comment by jwang98052** [comment]
No progress on it. I agree we should postpone it after 0.16 is out.

**Comment by markusweimer** [comment]
@inchiosa, can you close this PR then until 0.16 is out?

**Pull request closed without merging**
