### PR TITLE
[REEF-2002] Create Java project for gRPC two process bridge

### PR DESCRIPTION
**Pull request by tcondie**
This addressed the issue by
  * Adding gRPC bridge implementation
  * Implemeting event handlers and objects that pass between application
  and core driver.

JIRA:
  [REEF-2002](https://issues.apache.org/jira/browse/REEF-2002)

Pull request:
    This closes #

### CODE REVIEW

**Comment by dougmsft** [comment]
I am going to test and if successful pull this request into the REEF-335 branch later today.

**Comment by dougmsft** [comment]
Testing both Linux and Windows.

**Comment by dougmsft** [comment]
The java build and tests were successful on windows. On Linux I get the following error which I am rerunning.

java.io.IOException: Cannot run program "/bin/java" (in directory "./REEF_LOCAL_RUNTIME/Node-1-1523915326928"): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at org.apache.reef.runtime.local.process.RunnableProcess.run(RunnableProcess.java:196)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 2 more

Exception in thread "ProcessContainer:Node-1-1523915326928" java.lang.NullPointerException
	at org.apache.reef.runtime.local.process.RunnableProcess.run(RunnableProcess.java:213)
	at java.lang.Thread.run(Thread.java:748)

**Comment by dougmsft** [comment]
Both builds also produce this file now:

lang/java/reef-bridge-proto-java/dependency-reduced-pom.xml

**Comment by dougmsft** [comment]
You can close this as I have pull it into apache  REEF-335. Looks auto close on pull only works for master.

**Comment by tcondie** [comment]
Closing as per @dougmsft request.

**Pull request closed without merging**
