### PR TITLE
[REEF-1409] Upgrade HDP2.4 docker image to use 2.4.2 repository

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
This PR upgrades HDP2.4 docker images from HDP 2.4.0 into HDP 2.4.2.
HDInsight was already upgraded to use HDP 2.4.2 two weeks ago.
We had better upgrade ours to HDP 2.4.2.

JIRA:
  [REEF-1409](https://issues.apache.org/jira/browse/REEF-1409)

Pull Request:
  This closes #

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
This PR was tested on 0.16.0-SNAPSHOT.
```bash
root@hnn-001-01:/reef/bin# ./runyarntests.sh 
...
INFO: REEF Version: 0.16.0-SNAPSHOT
...
Time: 595.077

OK (35 tests)
```

**Comment by dongjoon-hyun** [comment]
Hi, @johnyangk .
Could you review this when you have some time?

**Comment by johnyangk** [comment]
@dongjoon-hyun Sure, I'll review it tomorrow. :)

**Comment by dongjoon-hyun** [comment]
Thank you always, @johnyangk !

**Comment by dongjoon-hyun** [comment]
Ping @johnyangk . :)

**Comment by johnyangk** [comment]
@dongjoon-hyun Sorry for the late response. The tests pass on my macbook. Merged it. :)

**Comment by dongjoon-hyun** [comment]
Thank you so much, @johnyangk !
You're fast. :-)

**Pull request closed without merging**
