### PR TITLE
[REEF-1487] Delete deprecated code in reef-io

### PR DESCRIPTION
**Pull request by tcNickolas**
This deletes code deprecated in release 0.14.

JIRA:
  [REEF-1487](https://issues.apache.org/jira/browse/REEF-1487)

Pull request:
  This closes #

### CODE REVIEW

**Comment by jsjason** [comment]
I have some code that may be affected by this, although it shouldn't; I'd like to check this.

**Comment by tcNickolas** [comment]
Please do, but this shouldn't block this PR from going in, unless I've inadvertently deleted some code which was not deprecated.

**Comment by jsjason** [comment]
@tcNickolas Looks great. One question though: why did you leave the deprecated code in `CommunicationGroupDriverImpl` untouched? It was originally on the JIRA description, right?

**Comment by tcNickolas** [comment]
Because for it deprecated constructor is used in code, and switch from explicit constructor call to injection is not quite trivial because two constructors have different sets of parameters. I've filed REEF-1488 for it so that it is not forgotten.

**Comment by jsjason** [comment]
Oh, didn't notice 1488. If so, this is safe to be merged. I'll merge this.

**Pull request closed without merging**
