### PR TITLE
Fix CoreCLR incompatibility in Tang Reflection Utilities

### PR DESCRIPTION
**Pull request by shsundr**
JIRA
https://issues.apache.org/jira/browse/REEF-1499

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Hi, @shsundr .
You had better change the title and commit message like the other PRs.
There is a format in REEF. The following is the commit log format for your issue. The title usually be the same with the first line of commit message.
```
[REEF-1499] Fix CoreCLR incompatibility in Tang
    
Your description.....
    
JIRA:
  [REEF-1499](https://issues.apache.org/jira/browse/REEF-1499)

This closes #
```

**Comment by dongjoon-hyun** [comment]
Why?

**Comment by shsundr** [comment]
I created a new pull request #1081 with the properly formatted commit message

**Comment by dongjoon-hyun** [comment]
Oh, you can use `git commit --amend` and `git push -f` for that purpose.

**Comment by shravanmn** [comment]
Yep, or rebase.

**Comment by shsundr** [comment]
Thanks,  I will use rebase next time, if necessary
-Shiv

**Comment by dongjoon-hyun** [comment]
Rebase does not change the commit message. Also, if the master have no change, `rebase` will be ignored. :)

**Pull request closed without merging**
