### PR TITLE
[REEF-1270] Update the website for 0.14.0

### PR DESCRIPTION
**Pull request by yunseong**
JIRA:
  [REEF-1270](https://issues.apache.org/jira/browse/REEF-1270)

Pull Request:
  Closes #

### CODE REVIEW

**Comment by yunseong** [comment]
Please wait, this should not be merged as `mvn site:site` fails because of the `&` character in the URL of the release note. I'll fix the issue, and update the `update_website.py` script.

**Comment by yunseong** [comment]
Now I've checked the latest change (&-> &amp; in the ReleaseNote link) makes `mvn site:site` pass. @markusweimer @tcNickolas Could you take a look and merge this?

**Comment by tcNickolas** [comment]
Can you add the change in `update_website.py` script ?
Also, for this PR you can add `[ci skip]` to commit message so as not to build up Travis queue.

**Comment by yunseong** [comment]
@tcNickolas Thanks for your thoughtful comments (including ci tips)!

I've updated the script. Could you take another look? Thanks a lot!

**Comment by tcNickolas** [comment]
I've verified that update in script leaves `&amp;` sequence unchanged and replaces standalone `&`. I don't think we'll ever have other `&...;` sequences in our links, so that's good enough for now.
The change in website also looks good. I'll merge

**Pull request closed without merging**
