### PR TITLE
[REEF-1803]  Fix build break in master for not follow RAT rule

### PR DESCRIPTION
**Pull request by jwang98052**
Fix missing license header in NuGet.config

JIRA: REEF-1803
This closes #

### CODE REVIEW

**Comment by singlis** [comment]
Ah! Thank you for fixing this.

**Comment by dougmsft** [comment]
Verifying build for commit.

**Comment by dougmsft** [comment]
I am seeing a build error from Maven:

Results :

Failed tests:
  FailTaskTest.testFailTaskStop:86->failOn:52 expected:<FAILED> but was:<COMPLETED>

Tests run: 68, Failures: 1, Errors: 0, Skipped: 1

**Comment by jwang98052** [comment]
Those test failures are frequently seeing transit failures. The change is to add comments that should only impact build.

**Pull request closed without merging**
