### PR TITLE
 [REEF-1991] Delete old project, rename DotNet projects to old project names

### PR DESCRIPTION
**Pull request by singlis**
This change removes all the old projects and renames the new projects
 to the old project names (effectively removing the "DotNet" name).
 Changes include the following:
 - Deletes old projects
 - Renames all *.DotNet.csproj to *.csproj
 - Renames all AssemblyInfo.DotNet.cs to AssemblyInfo.cs. If
   the project only had an AssemblyInfo.cs, this was deleted since its
   specified now in the csproj file.
 - Removed all packages.config
 - Removed all *.nuspec.
 - Updates to appveyor.xml for building.

JIRA:
    [REEF-1991](https://issues.apache.org/jira/browse/REEF-1991)

Pull Request:
    This closes #

### CODE REVIEW

**Comment by markusweimer** [comment]
I built it nonetheless after that error, and got the following errors:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Assets file 'D:\src\reef\lang\cs\Org.Apache.REEF.Utilities\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	Org.Apache.REEF.Utilities	C:\Program Files\dotnet\sdk\2.1.201\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets	327	
Error		Assets file 'D:\src\reef\lang\cs\Org.Apache.REEF.Utilities\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	Org.Apache.REEF.Utilities	C:\Program Files\dotnet\sdk\2.1.201\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets	167	
Error		Assets file 'D:\src\reef\lang\cs\Org.Apache.REEF.Tang\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	Org.Apache.REEF.Tang	C:\Program Files\dotnet\sdk\2.1.201\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets	327	
Error		Assets file 'D:\src\reef\lang\cs\Org.Apache.REEF.Tang\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	Org.Apache.REEF.Tang	C:\Program Files\dotnet\sdk\2.1.201\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets	167	
Error		Assets file 'D:\src\reef\lang\cs\Org.Apache.REEF.Wake\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	Org.Apache.REEF.Wake	C:\Program Files\dotnet\sdk\2.1.201\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets	327	
Error		Assets file 'D:\src\reef\lang\cs\Org.Apache.REEF.Wake\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	Org.Apache.REEF.Wake	C:\Program Files\dotnet\sdk\2.1.201\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets	167	
Error		Assets file 'D:\src\reef\lang\cs\Org.Apache.REEF.Common\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	Org.Apache.REEF.Common	C:\Program Files\dotnet\sdk\2.1.201\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets	327	
Error		Assets file 'D:\src\reef\lang\cs\Org.Apache.REEF.Common\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	Org.Apache.REEF.Common	C:\Program Files\dotnet\sdk\2.1.201\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets	167	
Error		Assets file 'D:\src\reef\lang\cs\Org.Apache.REEF.Driver\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	Org.Apache.REEF.Driver	C:\Program Files\dotnet\sdk\2.1.201\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets	327	
Error		Assets file 'D:\src\reef\lang\cs\Org.Apache.REEF.Driver\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	Org.Apache.REEF.Driver	C:\Program Files\dotnet\sdk\2.1.201\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets	167	
Error		Assets file 'D:\src\reef\lang\cs\Org.Apache.REEF.Tang.Examples\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	Org.Apache.REEF.Tang.Examples	C:\Program Files\dotnet\sdk\2.1.201\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets	327	
Error		Assets file 'D:\src\reef\lang\cs\Org.Apache.REEF.Tang.Examples\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	Org.Apache.REEF.Tang.Examples	C:\Program Files\dotnet\sdk\2.1.201\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets	167	
Error		Assets file 'D:\src\reef\lang\cs\Org.Apache.REEF.Wake.Tests\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	Org.Apache.REEF.Wake.Tests	C:\Program Files\dotnet\sdk\2.1.201\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets	327	
Error		Assets file 'D:\src\reef\lang\cs\Org.Apache.REEF.Wake.Tests\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	Org.Apache.REEF.Wake.Tests	C:\Program Files\dotnet\sdk\2.1.201\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets	167	
Error		Assets file 'D:\src\reef\lang\cs\Org.Apache.REEF.Network\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	Org.Apache.REEF.Network	C:\Program Files\dotnet\sdk\2.1.201\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets	327	
Error		Assets file 'D:\src\reef\lang\cs\Org.Apache.REEF.Network\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	Org.Apache.REEF.Network	C:\Program Files\dotnet\sdk\2.1.201\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets	167	
Error		Assets file 'D:\src\reef\lang\cs\Org.Apache.REEF.Network.Examples\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	Org.Apache.REEF.Network.Examples	C:\Program Files\dotnet\sdk\2.1.201\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets	327	
Error		Assets file 'D:\src\reef\lang\cs\Org.Apache.REEF.Network.Examples\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	Org.Apache.REEF.Network.Examples	C:\Program Files\dotnet\sdk\2.1.201\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets	167	
Error		Assets file 'D:\src\reef\lang\cs\Org.Apache.REEF.Examples\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	Org.Apache.REEF.Examples	C:\Program Files\dotnet\sdk\2.1.201\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets	327	
Error		Assets file 'D:\src\reef\lang\cs\Org.Apache.REEF.Examples\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	Org.Apache.REEF.Examples	C:\Program Files\dotnet\sdk\2.1.201\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets	167	
Error		Assets file 'D:\src\reef\lang\cs\Org.Apache.REEF.Common.Tests\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	Org.Apache.REEF.Common.Tests	C:\Program Files\dotnet\sdk\2.1.201\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets	327	
Error		Assets file 'D:\src\reef\lang\cs\Org.Apache.REEF.Common.Tests\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	Org.Apache.REEF.Common.Tests	C:\Program Files\dotnet\sdk\2.1.201\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets	167	
Error		Assets file 'D:\src\reef\lang\cs\Org.Apache.REEF.IO\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	Org.Apache.REEF.IO	C:\Program Files\dotnet\sdk\2.1.201\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets	327	
Error		Assets file 'D:\src\reef\lang\cs\Org.Apache.REEF.IO\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	Org.Apache.REEF.IO	C:\Program Files\dotnet\sdk\2.1.201\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets	167	
Error		Assets file 'D:\src\reef\lang\cs\Org.Apache.REEF.Tang.Tools\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	Org.Apache.REEF.Tang.Tools	C:\Program Files\dotnet\sdk\2.1.201\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets	327	
Error		Assets file 'D:\src\reef\lang\cs\Org.Apache.REEF.Tang.Tools\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	Org.Apache.REEF.Tang.Tools	C:\Program Files\dotnet\sdk\2.1.201\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets	167	
Error		Assets file 'D:\src\reef\lang\cs\Org.Apache.REEF.Network.Tests\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	Org.Apache.REEF.Network.Tests	C:\Program Files\dotnet\sdk\2.1.201\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets	327	
Error		Assets file 'D:\src\reef\lang\cs\Org.Apache.REEF.Network.Tests\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	Org.Apache.REEF.Network.Tests	C:\Program Files\dotnet\sdk\2.1.201\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets	167	
Error		Assets file 'D:\src\reef\lang\cs\Org.Apache.REEF.Tang.Tests\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	Org.Apache.REEF.Tang.Tests	C:\Program Files\dotnet\sdk\2.1.201\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets	327	
Error		Assets file 'D:\src\reef\lang\cs\Org.Apache.REEF.Tang.Tests\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	Org.Apache.REEF.Tang.Tests	C:\Program Files\dotnet\sdk\2.1.201\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets	167	
Error		Assets file 'D:\src\reef\lang\cs\Org.Apache.REEF.IO.Tests\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	Org.Apache.REEF.IO.Tests	C:\Program Files\dotnet\sdk\2.1.201\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets	327	
Error		Assets file 'D:\src\reef\lang\cs\Org.Apache.REEF.IO.Tests\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	Org.Apache.REEF.IO.Tests	C:\Program Files\dotnet\sdk\2.1.201\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets	167	
Error		Assets file 'D:\src\reef\lang\cs\Org.Apache.REEF.Bridge.CLR\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	Org.Apache.REEF.Bridge.CLR	C:\Program Files\dotnet\sdk\2.1.201\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets	327	
Error		Assets file 'D:\src\reef\lang\cs\Org.Apache.REEF.Bridge.CLR\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	Org.Apache.REEF.Bridge.CLR	C:\Program Files\dotnet\sdk\2.1.201\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets	167	
Error		Assets file 'D:\src\reef\lang\cs\Org.Apache.REEF.Evaluator\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	Org.Apache.REEF.Evaluator	C:\Program Files\dotnet\sdk\2.1.201\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets	327	
Error		Assets file 'D:\src\reef\lang\cs\Org.Apache.REEF.Evaluator\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	Org.Apache.REEF.Evaluator	C:\Program Files\dotnet\sdk\2.1.201\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets	167	
Error	C1192	#using failed on 'D:\src\reef\lang\cs\bin\.netcore\Debug\Org.Apache.REEF.Driver\netstandard2.0\Org.Apache.REEF.Driver.dll'	Org.Apache.REEF.Bridge	d:\src\reef\lang\cs\org.apache.reef.bridge\stdafx.cpp	1	
Error		Assets file 'D:\src\reef\lang\cs\Org.Apache.REEF.Client\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	Org.Apache.REEF.Client	C:\Program Files\dotnet\sdk\2.1.201\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets	327	
Error		Assets file 'D:\src\reef\lang\cs\Org.Apache.REEF.Client\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	Org.Apache.REEF.Client	C:\Program Files\dotnet\sdk\2.1.201\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets	167	
Error		Assets file 'D:\src\reef\lang\cs\Org.Apache.REEF.Client.Tests\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	Org.Apache.REEF.Client.Tests	C:\Program Files\dotnet\sdk\2.1.201\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets	327	
Error		Assets file 'D:\src\reef\lang\cs\Org.Apache.REEF.Client.Tests\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	Org.Apache.REEF.Client.Tests	C:\Program Files\dotnet\sdk\2.1.201\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets	167	
Error		Assets file 'D:\src\reef\lang\cs\Org.Apache.REEF.Examples.AllHandlers\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	Org.Apache.REEF.Examples.AllHandlers	C:\Program Files\dotnet\sdk\2.1.201\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets	327	
Error		Assets file 'D:\src\reef\lang\cs\Org.Apache.REEF.Examples.AllHandlers\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	Org.Apache.REEF.Examples.AllHandlers	C:\Program Files\dotnet\sdk\2.1.201\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets	167	
Error		Assets file 'D:\src\reef\lang\cs\Org.Apache.REEF.Examples.HelloREEF\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	Org.Apache.REEF.Examples.HelloREEF	C:\Program Files\dotnet\sdk\2.1.201\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets	327	
Error		Assets file 'D:\src\reef\lang\cs\Org.Apache.REEF.Examples.HelloREEF\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	Org.Apache.REEF.Examples.HelloREEF	C:\Program Files\dotnet\sdk\2.1.201\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets	167	
Error		Assets file 'D:\src\reef\lang\cs\Org.Apache.REEF.IMRU\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	Org.Apache.REEF.IMRU	C:\Program Files\dotnet\sdk\2.1.201\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets	327	
Error		Assets file 'D:\src\reef\lang\cs\Org.Apache.REEF.IMRU\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	Org.Apache.REEF.IMRU	C:\Program Files\dotnet\sdk\2.1.201\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets	167	
Error		Assets file 'D:\src\reef\lang\cs\Org.Apache.REEF.Network.Examples.Client\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	Org.Apache.REEF.Network.Examples.Client	C:\Program Files\dotnet\sdk\2.1.201\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets	327	
Error		Assets file 'D:\src\reef\lang\cs\Org.Apache.REEF.Network.Examples.Client\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	Org.Apache.REEF.Network.Examples.Client	C:\Program Files\dotnet\sdk\2.1.201\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets	167	
Error		Assets file 'D:\src\reef\lang\cs\Org.Apache.REEF.IO.TestClient\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	Org.Apache.REEF.IO.TestClient	C:\Program Files\dotnet\sdk\2.1.201\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets	327	
Error		Assets file 'D:\src\reef\lang\cs\Org.Apache.REEF.IO.TestClient\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	Org.Apache.REEF.IO.TestClient	C:\Program Files\dotnet\sdk\2.1.201\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets	167	
Error		Assets file 'D:\src\reef\lang\cs\Org.Apache.REEF.Examples.DriverRestart\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	Org.Apache.REEF.Examples.DriverRestart	C:\Program Files\dotnet\sdk\2.1.201\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets	327	
Error		Assets file 'D:\src\reef\lang\cs\Org.Apache.REEF.Examples.DriverRestart\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	Org.Apache.REEF.Examples.DriverRestart	C:\Program Files\dotnet\sdk\2.1.201\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets	167	
Error		Assets file 'D:\src\reef\lang\cs\Org.Apache.REEF.IMRU.Examples\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	Org.Apache.REEF.IMRU.Examples	C:\Program Files\dotnet\sdk\2.1.201\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets	327	
Error		Assets file 'D:\src\reef\lang\cs\Org.Apache.REEF.IMRU.Examples\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	Org.Apache.REEF.IMRU.Examples	C:\Program Files\dotnet\sdk\2.1.201\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets	167	
Error		Assets file 'D:\src\reef\lang\cs\Org.Apache.REEF.Evaluator.Tests\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	Org.Apache.REEF.Evaluator.Tests	C:\Program Files\dotnet\sdk\2.1.201\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets	327	
Error		Assets file 'D:\src\reef\lang\cs\Org.Apache.REEF.Evaluator.Tests\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	Org.Apache.REEF.Evaluator.Tests	C:\Program Files\dotnet\sdk\2.1.201\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets	167	
Error		Assets file 'D:\src\reef\lang\cs\Org.Apache.REEF.FatNuGet\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	Org.Apache.REEF.FatNuGet	C:\Program Files\dotnet\sdk\2.1.201\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets	327	
Error		Assets file 'D:\src\reef\lang\cs\Org.Apache.REEF.FatNuGet\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	Org.Apache.REEF.FatNuGet	C:\Program Files\dotnet\sdk\2.1.201\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets	167	
Error		Assets file 'D:\src\reef\lang\cs\Org.Apache.REEF.IMRU.Tests\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	Org.Apache.REEF.IMRU.Tests	C:\Program Files\dotnet\sdk\2.1.201\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets	327	
Error		Assets file 'D:\src\reef\lang\cs\Org.Apache.REEF.IMRU.Tests\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	Org.Apache.REEF.IMRU.Tests	C:\Program Files\dotnet\sdk\2.1.201\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets	167	
Error		Assets file 'D:\src\reef\lang\cs\Org.Apache.REEF.Tests\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	Org.Apache.REEF.Tests	C:\Program Files\dotnet\sdk\2.1.201\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets	327	
Error		Assets file 'D:\src\reef\lang\cs\Org.Apache.REEF.Tests\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	Org.Apache.REEF.Tests	C:\Program Files\dotnet\sdk\2.1.201\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets	167	
```

**Comment by singlis** [comment]
Thank Markus for testing. I am not sure about the guid error -- I am using VS 15.5. So I will upgrade to 15.7 to see if I can reproduce it. As for the missing project.assets.json, that sounds like the packages are not restored. If you are building from the command line, you have to do this manually with an msbuild Org.Apache.REEF.sln /t:restore before doing the build. The restore does happen automatically when you build within VS.

**Comment by markusweimer** [comment]
> The restore does happen automatically when you build within VS.

I am building in VS, and it doesn't seem to happen automatically :(

**Comment by singlis** [comment]
So this was due to a malformed sln file that would load OK with 15.5 but fails in 15.7. I have pushed up a change that fixes the sln file in this PR, but let me know if this fix would be better off being in its own PR.

**Pull request closed without merging**
