### PR TITLE
[REEF-1238] Remove obsolete .NET code in O.A.R.Wake and O.A.R.Driver

### PR DESCRIPTION
**Pull request by tcNickolas**
This change removes obsolete code related to:
 * MaxApplicationSubmissions in YARN job submission parameters
 * Wake Codec creation
 * handler GC in ClrHandlerHelper
 * DefaultEvaluatorRequestorHandler

JIRA:
  [REEF-1238](https://issues.apache.org/jira/browse/REEF-1238)

Pull request:
  This closes #

### CODE REVIEW

**Comment by tcNickolas** [comment]
@afchung This PR removes a lot of classes/fields deprecated by you. Could you please take a look? I'm interested in `MaxApplicationSubmissions`, since it's the only field that was still in use in code.

**Comment by afchung** [comment]
This looks good to me. For `MaxApplicationSubmissions`, in my previous change, I moved it to not be Tang-based, provided that it is a submission-time parameter that should not be merged into a job runtime configuration in the first place. @tcNickolas do you have any concerns with it? If not, I'll test and merge. Thanks!

**Comment by tcNickolas** [comment]
My only concern was that I misread your intention for it, and you wanted it not deleted but made private or something.

**Comment by afchung** [comment]
OK sounds good! I'll test and merge.

**Pull request closed without merging**
