### PR TITLE
[REEF-1909] Fix Compilation errors in VSC++ 2013 and 2015

### PR DESCRIPTION
**Pull request by jwang98052**
JIRA: [REEF-1909](https://issues.apache.org/jira/browse/REEF-1909)
This closes #

### CODE REVIEW

**Comment by tcNickolas** [comment]
Has `TestResubmitEvaluator` test been failing before? It fails in all three builds, I don't remember it in the transient test failures but it's been a while since I looked at it

**Comment by jwang98052** [comment]
I will look at it.

**Comment by dougmsft** [comment]
I am seeing a test failure when I build locally which I am investigating.

**Comment by motus** [comment]
@tcNickolas `TestResubmitEvaluator` fails in current master. I can reproduce the failure on my PC in VS2017. I've opened [REEF1910](https://issues.apache.org/jira/browse/REEF-1910) issue in JIRA to track the problem and assigned it to @jwang98052 temporarily. I will test and merge this PR, though - at least it reduces the number of test failures 😄

**Pull request closed without merging**
