### PR TITLE
[REEF-1398] Update version to 0.16.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by shulmanb**
This addresses the issue by updating the versions to 0.16.0-SNAPSHOT
JIRA:
    [REEF-1398](https://issues.apache.org/jira/browse/REEF-1398)

### CODE REVIEW

**Comment by markusweimer** [comment]
I haven't seen the branch for 0.15 yet. Are you sure this is a good idea right now?

**Comment by shulmanb** [comment]
@markusweimer I am following the process as described in the Release Manager guide. Should I do something else?

**Comment by shulmanb** [comment]
@markusweimer Should I put RC1 for vote now or I should wait? I already pushed the branch.

**Comment by tcNickolas** [comment]
The branch is seen at https://git-wip-us.apache.org/repos/asf?p=reef.git (although it doesn't have tag release-0.15.0-rc1), so I think it's ok to proceed with updating the master branch with new version.

@shulmanb If all release-blocking issues have been resolved, yes you can proceed to call a vote on RC1.

**Comment by shulmanb** [comment]
@tcNickolas Rigth, forgot to tag it. Will do now.

**Comment by markusweimer** [comment]
I'll test and merge this.

**Pull request closed without merging**
