### PR TITLE
[REEF-1884] Fixed a missing `import` in `IFailureStateMachine.cs`

### PR DESCRIPTION
**Pull request by markusweimer**
JIRA:
  [REEF-1884](https://issues.apache.org/jira/browse/REEF-1884)

### CODE REVIEW

**Comment by markusweimer** [comment]
@motus or @jwang98052 , can you please test this ASAP? This fixes a syntax error which prevents any of our other pull requests from succeeding.

**Comment by jwang98052** [comment]
I will test and merge

**Comment by markusweimer** [comment]
Thank you @jwang98052 !

**Comment by jwang98052** [comment]
It won't build without that using. Just wonder how was it get checked in ;)

**Comment by jwang98052** [comment]
Two test failures are transit failures. Others are OK. I will merge now.

**Pull request closed without merging**
