### PR TITLE
[REEF-1252] Improve REEF main page on Github

### PR DESCRIPTION
**Pull request by tcNickolas**
This change rearranges content and adds several badges
reflecting project status.

JIRA:
  [REEF-1252](https://issues.apache.org/jira/browse/REEF-1252)

Pull request:
  This closes #

### CODE REVIEW

**Comment by tcNickolas** [comment]
The change can be previewed at https://github.com/tcNickolas/reef/tree/REEF-1252/

I'm open to suggestions for other information that would be nice to reflect on this page.

**Comment by zerg-junior** [comment]
> Apache REEF™ (Retainable Evaluator Execution Framework) is a scale-out computing fabric

In my expierence, saying that REEF is a standard library for building distributed systems works much better. The "fabric" sounds way too vague for many people.

>For example, Azure Stream Analytics is built on REEF

My academic background tells me this statement asks for a reference :)


> The developer mailinglist 

Small typo: mailinglist -> mailing list

> other information that would be nice to reflect on this page

The current release version as a badge would be nice.

**Comment by zerg-junior** [comment]
Can you please leave this pull request for me to accept ? I need to learn how to do this.

**Comment by tcNickolas** [comment]
@markusweimer, could you please comment on the suggested text changes?

Current release version means adding it to our version update script, as we don't have a way to extract this information automatically. I think we can add badges to downloads page and to nuget.org page, and the exact version doesn't really matter in this context.

**Comment by markusweimer** [comment]
I think we do in fact have a discussion about how to summarize REEF in a single sentence. Let's move that to the dev list and proceed here without changing those statements.

**Comment by tcNickolas** [comment]
+1. Then we can do update without CR based on it being documentation :-)
@zerg-junior I've addressed the rest of the comments.

**Comment by zerg-junior** [comment]
@tcNickolas Should we add [this MS blog post](https://blogs.microsoft.com/firehose/2015/12/17/apache-reef-backbone-of-azure-stream-analytics-and-more-achieves-major-milestone/#sm.0001auimm3k6xcogz3k2jplh106oh) and the link to Dolphin as examples of REEF usage  ?

**Comment by markusweimer** [comment]
> Should we add this MS blog post and the link to Dolphin as examples of REEF usage ?

Maybe. However, if we add one, I'd prefer [this one](https://blogs.technet.microsoft.com/machinelearning/2015/12/17/reef-graduates-to-a-top-level-apache-project/) :)

**Comment by zerg-junior** [comment]
@tcNickolas  I'll update and merge

**Comment by zerg-junior** [comment]
@tcNickolas Have I preserved your authorship everywhere I should have ?

@markusweimer Review the main page, please.

**Comment by tcNickolas** [comment]
Yes, looks good. Thank you!

**Pull request closed without merging**
