### PR TITLE
[REEF-1220] Change REEF versions in Avro-format config file

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
JIRA:
  [REEF-1220] https://issues.apache.org/jira/browse/REEF-1220

Pull Request:
  Closes #

### CODE REVIEW

**Comment by yunseong** [comment]
This PR addresses the build failure but I'm not 100% sure that this approach fixes the problem entirely; we need to refactor the example code to avoid using the hard-coded version, then we don't have to update those files in this script.

We can tackle the refactoring in a separate PR, though at least it'd be good to have `TODO` to track this issue in the future. @markusweimer Any thought?

**Comment by dongjoon-hyun** [comment]
+1 to remove `hard-coded version`. I really agree with you!
In fact, I don't like `change_verson.py`.

**Comment by markusweimer** [comment]
I believe this is a test we wanted to delete in an earlier PR. The reason to remove the test brought forward by @afchung was to address exactly this issue: The file is a "magic" file in the tests that should really be generated correctly as part of the test instead of materialization in the repository. @jwang98052 wanted to keep it.

Can I ask @afchung and @jwang98052 to comment on the issue? I currently fall on the "delete the test" side of the argument, as the test is bound to create problems like this while at the same time, it doesn't really test the real scenario.

**Comment by jwang98052** [comment]
Why you need to change the version in those two config files? Is it because you scanned the source and find there is version inside the files? 

Those two files are used as input of unit testing. It does test the code like alias classes we defined for Evaluator. 

The version info is not used in the testing. We don't need to replace it. If we don't like any file as unit testing input, we can put the content as static string in unit tests as a separate Jira.

**Comment by dongjoon-hyun** [comment]
Hi, @jwang98052 . 
Could you read #852 first? After changing version, the tests fails.
I made this PR to help that. I thought we had two options: removing the test cases or changing it to new version.

**Comment by dongjoon-hyun** [comment]
FYI, on my PC with clean clone, old `change_version.py` makes build failures due to that resource files, too. With this PR, I can pass the tests.

**Comment by jwang98052** [comment]
I see. It is caused by the Task and Context Configuration which is based on the current version. 
I have created REEF-1221 to remove this dependency.

**Comment by dongjoon-hyun** [comment]
Great! Then, I'll close this PR now.

**Pull request closed without merging**
