### PR TITLE
[REEF-1633] Implement Tang.getDefaultSerializer() and .toString() methods

### PR DESCRIPTION
**Pull request by motus**
Also, use `Tang.toString()` in REEF examples

JIRA: [REEF-1633](https://issues.apache.org/jira/browse/REEF-1633)

### CODE REVIEW

**Comment by markusweimer** [comment]
Can we move `Tang.toString()` to `Configurations.prettyPrint()`? That seems like a more logical place to me.

**Comment by motus** [comment]
@markusweimer souds good, but then we'll have to move there `.getDefaultSerializer()`, too, because all these methods require a serializer. WDYT?

**Comment by markusweimer** [comment]
> but then we'll have to move the `.getDefaultSerializer()`, too

+1

It also sounds better than the alternative in `Tang`

**Comment by motus** [comment]
@markusweimer ok let me do this now

**Comment by motus** [comment]
@markusweimer here's the change. much less invasive than the first version, too.

**Comment by markusweimer** [comment]
LGTM, will test and merge

**Comment by motus** [comment]
@markusweimer squished commits into one

**Pull request closed without merging**
