### PR TITLE
[REEF-1055] Enable StyleCop.CSharp.ReadabilityRules and fix violations

### PR DESCRIPTION
**Pull request by tcNickolas**
This enables the following rules:
 * CommentsMustContainText
 * DoNotPrefixCallsWithBaseUnlessLocalImplementationExists
 * OpeningParenthesisMustBeOnDeclarationLine
 * ClosingParenthesisMustBeOnLineOfLastParameter
 * ClosingParenthesisMustBeOnLineOfOpeningParenthesis
 * CommaMustBeOnSameLineAsPreviousParameter
 * ParameterListMustFollowDeclaration
 * ParameterMustNotSpanMultipleLines
 * QueryClauseMustFollowPreviousClause
 * QueryClausesMustBeOnSeparateLinesOrAllOnOneLine
 * QueryClauseMustBeginOnNewLineWhenPreviousClauseSpansMultipleLines
 * QueryClausesSpanningMultipleLinesMustBeginOnOwnLine
 * DoNotPlaceRegionsWithinElements
 * CodeMustNotContainEmptyStatements
 * CodeMustNotContainMultipleStatementsOnOneLine
 * BlockStatementsMustNotContainEmbeddedComments
 * BlockStatementsMustNotContainEmbeddedRegions
 * UseStringEmptyForEmptyStrings
 * UseBuiltInTypeAlias
 * UseShorthandForNullableTypes

JIRA:
  [REEF-1055](https://issues.apache.org/jira/browse/REEF-1055)

Pull request:
  This closes #

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Hi, @tcNickolas . It looks good to me. I'll test and merge this.

**Comment by dongjoon-hyun** [comment]
@tcNickolas . Could you test this PR again? During building, 162 violations occur. The majority of the violations are SA1121 in `Tang` module, but the other modules like `Wake` also have violations, too.

**Comment by tcNickolas** [comment]
Sure, I'll double-check. Maybe VS cached build of some projects and didn't re-build them with StyleCop enabled.

**Comment by tcNickolas** [comment]
Indeed, when I deleted cs/bin folder there were plenty more violations. I've updated PR to have them fixed

**Comment by tcNickolas** [comment]
I've resolved conflicts and updated PR. Would be nice if someone took a look before more .NET code gets committed (and produces more violations).

**Comment by markusweimer** [comment]
I assume none of the changes are functional? In which case I can test and merge.

**Comment by tcNickolas** [comment]
No functional changes. At most introducing local variable to hold result of string.format before logging it.

**Comment by markusweimer** [comment]
OK, tests pass, I will merge.

**Pull request closed without merging**
