### PR TITLE
[REEF-1764] Create NuGet for IMRU Examples

### PR DESCRIPTION
**Pull request by jwang98052**
JIRA: [REEF-1764](https://issues.apache.org/jira/browse/REEF-1764)
This closes  #

### CODE REVIEW

**Comment by markusweimer** [comment]
LGTM, will test and merge.

**Comment by markusweimer** [comment]
@jwang98052 I merged this, but somehow the PR isn't closed. Can you please close manually?

**Comment by jwang98052** [comment]
merged.

**Comment by jwang98052** [comment]
@markusweimer  Looks like the replication doesn't work as the change is shown together with a new PL I am trying to submit.

**Pull request closed without merging**
