### PR TITLE
[REEF-1930] Update environmentVariablesMap name in .Net code

### PR DESCRIPTION
**Pull request by jwang98052**
* Rename envMap to environmentVariablesMap
* Remove the real env varaible in HelloREEFYarn as it impacts the teting.

JIRA: [REEF-1930](https://issues.apache.org/jira/browse/REEF-1930)
This closes #

### CODE REVIEW

**Comment by markusweimer** [comment]
I get a bunch of test failures:

```
Test Name:	Org.Apache.REEF.Tests.Functional.Bridge.TestSecurityToken.TestSecurityTokenBackwardCompatibility
Test FullName:	Org.Apache.REEF.Tests.Functional.Bridge.TestSecurityToken.TestSecurityTokenBackwardCompatibility
Test Source:	D:\src\reef\lang\cs\Org.Apache.REEF.Tests\Functional\Bridge\TestSecurityToken.cs : line 81
Test Outcome:	Failed
Test Duration:	0:00:00.021

Result StackTrace:	
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Org.Apache.REEF.Utilities.Diagnostics.Exceptions.Throw(Exception exception, String message, Logger logger) in D:\src\reef\lang\cs\Org.Apache.REEF.Utilities\Diagnostics\Exceptions.cs:line 55
   at Org.Apache.REEF.Utilities.Diagnostics.Exceptions.Throw(Exception exception, Logger logger) in D:\src\reef\lang\cs\Org.Apache.REEF.Utilities\Diagnostics\Exceptions.cs:line 73
   at Org.Apache.REEF.Tang.Implementations.InjectionPlan.InjectorImpl.InjectFromPlan(InjectionPlan plan) in D:\src\reef\lang\cs\Org.Apache.REEF.Tang\Implementations\InjectionPlan\InjectorImpl.cs:line 188
   at Org.Apache.REEF.Tang.Implementations.InjectionPlan.InjectorImpl.InjectFromPlan(InjectionPlan plan) in D:\src\reef\lang\cs\Org.Apache.REEF.Tang\Implementations\InjectionPlan\InjectorImpl.cs:line 198
   at Org.Apache.REEF.Tang.Implementations.InjectionPlan.InjectorImpl.InjectFromPlan(InjectionPlan plan) in D:\src\reef\lang\cs\Org.Apache.REEF.Tang\Implementations\InjectionPlan\InjectorImpl.cs:line 198
   at Org.Apache.REEF.Tang.Implementations.InjectionPlan.InjectorImpl.InjectFromPlan(InjectionPlan plan) in D:\src\reef\lang\cs\Org.Apache.REEF.Tang\Implementations\InjectionPlan\InjectorImpl.cs:line 146
   at Org.Apache.REEF.Tang.Implementations.InjectionPlan.InjectorImpl.InjectFromPlan(InjectionPlan plan) in D:\src\reef\lang\cs\Org.Apache.REEF.Tang\Implementations\InjectionPlan\InjectorImpl.cs:line 198
   at Org.Apache.REEF.Tang.Implementations.InjectionPlan.InjectorImpl.InjectFromPlan(InjectionPlan plan) in D:\src\reef\lang\cs\Org.Apache.REEF.Tang\Implementations\InjectionPlan\InjectorImpl.cs:line 146
   at Org.Apache.REEF.Tang.Implementations.InjectionPlan.InjectorImpl.InjectFromPlan(InjectionPlan plan) in D:\src\reef\lang\cs\Org.Apache.REEF.Tang\Implementations\InjectionPlan\InjectorImpl.cs:line 198
   at Org.Apache.REEF.Tang.Implementations.InjectionPlan.InjectorImpl.GetInstance(INode node) in D:\src\reef\lang\cs\Org.Apache.REEF.Tang\Implementations\InjectionPlan\InjectorImpl.cs:line 781
   at Org.Apache.REEF.Tang.Implementations.InjectionPlan.InjectorImpl.GetInstance(String clazz) in D:\src\reef\lang\cs\Org.Apache.REEF.Tang\Implementations\InjectionPlan\InjectorImpl.cs:line 797
   at Org.Apache.REEF.Tang.Implementations.InjectionPlan.InjectorImpl.GetInstance[T]() in D:\src\reef\lang\cs\Org.Apache.REEF.Tang\Implementations\InjectionPlan\InjectorImpl.cs:line 764
   at Org.Apache.REEF.Tests.Functional.Bridge.TestSecurityToken.TestRun(IConfiguration config) in D:\src\reef\lang\cs\Org.Apache.REEF.Tests\Functional\Bridge\TestSecurityToken.cs:line 105
   at Org.Apache.REEF.Tests.Functional.Bridge.TestSecurityToken.TestSecurityTokenBackwardCompatibility() in D:\src\reef\lang\cs\Org.Apache.REEF.Tests\Functional\Bridge\TestSecurityToken.cs:line 82
----- Inner Stack Trace -----
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.ConstructorInfo.Invoke(Object[] parameters)
   at Org.Apache.REEF.Tang.Implementations.InjectionPlan.InjectorImpl.InjectFromPlan(InjectionPlan plan) in D:\src\reef\lang\cs\Org.Apache.REEF.Tang\Implementations\InjectionPlan\InjectorImpl.cs:line 164
----- Inner Stack Trace -----
   at Org.Apache.REEF.Utilities.Runtime.Yarn.YarnConfiguration..ctor(String hadoopConfDir, String yarnConfigFileName, Nullable`1 useHttps) in D:\src\reef\lang\cs\Org.Apache.REEF.Utilities\Runtime\Yarn\YarnConfiguration.cs:line 103
   at Org.Apache.REEF.Utilities.Runtime.Yarn.YarnConfiguration.GetConfiguration(String hadoopConfDir, String yarnConfigFileName, Nullable`1 useHttps) in D:\src\reef\lang\cs\Org.Apache.REEF.Utilities\Runtime\Yarn\YarnConfiguration.cs:line 82
   at Org.Apache.REEF.Client.Yarn.RestClient.YarnConfigurationUrlProvider..ctor(String hadoopConfigDir, Boolean useHttps) in D:\src\reef\lang\cs\Org.Apache.REEF.Client\YARN\RestClient\YarnConfigurationUrlProvider.cs:line 70
Result Message:	
Org.Apache.REEF.Tang.Exceptions.InjectionException : Could not invoke constructor: new Org.Apache.REEF.Client.Yarn.RestClient.YarnConfigurationUrlProvider(System.String Org.Apache.REEF.Client.Yarn.RestClient.YarnConfigurationUrlProvider+HadoopConfigurationDirectory =  , System.Boolean Org.Apache.REEF.Client.Yarn.RestClient.YarnConfigurationUrlProvider+UseHttpsForYarnCommunication = False)
---- System.Reflection.TargetInvocationException : Exception has been thrown by the target of an invocation.
-------- System.ArgumentException :  is not configured or does not exist.
```

```
Test Name:	Org.Apache.REEF.Tests.Functional.Bridge.TestSecurityToken.TestSetMultipleSecurityToken
Test FullName:	Org.Apache.REEF.Tests.Functional.Bridge.TestSecurityToken.TestSetMultipleSecurityToken
Test Source:	D:\src\reef\lang\cs\Org.Apache.REEF.Tests\Functional\Bridge\TestSecurityToken.cs : line 68
Test Outcome:	Failed
Test Duration:	0:00:00.007

Result StackTrace:	
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Org.Apache.REEF.Utilities.Diagnostics.Exceptions.Throw(Exception exception, String message, Logger logger) in D:\src\reef\lang\cs\Org.Apache.REEF.Utilities\Diagnostics\Exceptions.cs:line 55
   at Org.Apache.REEF.Utilities.Diagnostics.Exceptions.Throw(Exception exception, Logger logger) in D:\src\reef\lang\cs\Org.Apache.REEF.Utilities\Diagnostics\Exceptions.cs:line 73
   at Org.Apache.REEF.Tang.Implementations.InjectionPlan.InjectorImpl.InjectFromPlan(InjectionPlan plan) in D:\src\reef\lang\cs\Org.Apache.REEF.Tang\Implementations\InjectionPlan\InjectorImpl.cs:line 188
   at Org.Apache.REEF.Tang.Implementations.InjectionPlan.InjectorImpl.InjectFromPlan(InjectionPlan plan) in D:\src\reef\lang\cs\Org.Apache.REEF.Tang\Implementations\InjectionPlan\InjectorImpl.cs:line 198
   at Org.Apache.REEF.Tang.Implementations.InjectionPlan.InjectorImpl.InjectFromPlan(InjectionPlan plan) in D:\src\reef\lang\cs\Org.Apache.REEF.Tang\Implementations\InjectionPlan\InjectorImpl.cs:line 198
   at Org.Apache.REEF.Tang.Implementations.InjectionPlan.InjectorImpl.InjectFromPlan(InjectionPlan plan) in D:\src\reef\lang\cs\Org.Apache.REEF.Tang\Implementations\InjectionPlan\InjectorImpl.cs:line 146
   at Org.Apache.REEF.Tang.Implementations.InjectionPlan.InjectorImpl.InjectFromPlan(InjectionPlan plan) in D:\src\reef\lang\cs\Org.Apache.REEF.Tang\Implementations\InjectionPlan\InjectorImpl.cs:line 198
   at Org.Apache.REEF.Tang.Implementations.InjectionPlan.InjectorImpl.InjectFromPlan(InjectionPlan plan) in D:\src\reef\lang\cs\Org.Apache.REEF.Tang\Implementations\InjectionPlan\InjectorImpl.cs:line 146
   at Org.Apache.REEF.Tang.Implementations.InjectionPlan.InjectorImpl.InjectFromPlan(InjectionPlan plan) in D:\src\reef\lang\cs\Org.Apache.REEF.Tang\Implementations\InjectionPlan\InjectorImpl.cs:line 198
   at Org.Apache.REEF.Tang.Implementations.InjectionPlan.InjectorImpl.GetInstance(INode node) in D:\src\reef\lang\cs\Org.Apache.REEF.Tang\Implementations\InjectionPlan\InjectorImpl.cs:line 781
   at Org.Apache.REEF.Tang.Implementations.InjectionPlan.InjectorImpl.GetInstance(String clazz) in D:\src\reef\lang\cs\Org.Apache.REEF.Tang\Implementations\InjectionPlan\InjectorImpl.cs:line 797
   at Org.Apache.REEF.Tang.Implementations.InjectionPlan.InjectorImpl.GetInstance[T]() in D:\src\reef\lang\cs\Org.Apache.REEF.Tang\Implementations\InjectionPlan\InjectorImpl.cs:line 764
   at Org.Apache.REEF.Tests.Functional.Bridge.TestSecurityToken.TestRun(IConfiguration config) in D:\src\reef\lang\cs\Org.Apache.REEF.Tests\Functional\Bridge\TestSecurityToken.cs:line 105
   at Org.Apache.REEF.Tests.Functional.Bridge.TestSecurityToken.TestSetMultipleSecurityToken() in D:\src\reef\lang\cs\Org.Apache.REEF.Tests\Functional\Bridge\TestSecurityToken.cs:line 69
----- Inner Stack Trace -----
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.ConstructorInfo.Invoke(Object[] parameters)
   at Org.Apache.REEF.Tang.Implementations.InjectionPlan.InjectorImpl.InjectFromPlan(InjectionPlan plan) in D:\src\reef\lang\cs\Org.Apache.REEF.Tang\Implementations\InjectionPlan\InjectorImpl.cs:line 164
----- Inner Stack Trace -----
   at Org.Apache.REEF.Utilities.Runtime.Yarn.YarnConfiguration..ctor(String hadoopConfDir, String yarnConfigFileName, Nullable`1 useHttps) in D:\src\reef\lang\cs\Org.Apache.REEF.Utilities\Runtime\Yarn\YarnConfiguration.cs:line 103
   at Org.Apache.REEF.Utilities.Runtime.Yarn.YarnConfiguration.GetConfiguration(String hadoopConfDir, String yarnConfigFileName, Nullable`1 useHttps) in D:\src\reef\lang\cs\Org.Apache.REEF.Utilities\Runtime\Yarn\YarnConfiguration.cs:line 82
   at Org.Apache.REEF.Client.Yarn.RestClient.YarnConfigurationUrlProvider..ctor(String hadoopConfigDir, Boolean useHttps) in D:\src\reef\lang\cs\Org.Apache.REEF.Client\YARN\RestClient\YarnConfigurationUrlProvider.cs:line 70
Result Message:	
Org.Apache.REEF.Tang.Exceptions.InjectionException : Could not invoke constructor: new Org.Apache.REEF.Client.Yarn.RestClient.YarnConfigurationUrlProvider(System.String Org.Apache.REEF.Client.Yarn.RestClient.YarnConfigurationUrlProvider+HadoopConfigurationDirectory =  , System.Boolean Org.Apache.REEF.Client.Yarn.RestClient.YarnConfigurationUrlProvider+UseHttpsForYarnCommunication = False)
---- System.Reflection.TargetInvocationException : Exception has been thrown by the target of an invocation.
-------- System.ArgumentException :  is not configured or does not exist.

```

```
Test Name:	Org.Apache.REEF.Tests.Functional.Bridge.TestSecurityToken.TestSetOneSecurityToken
Test FullName:	Org.Apache.REEF.Tests.Functional.Bridge.TestSecurityToken.TestSetOneSecurityToken
Test Source:	D:\src\reef\lang\cs\Org.Apache.REEF.Tests\Functional\Bridge\TestSecurityToken.cs : line 93
Test Outcome:	Failed
Test Duration:	0:00:00.042

Result StackTrace:	
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Org.Apache.REEF.Utilities.Diagnostics.Exceptions.Throw(Exception exception, String message, Logger logger) in D:\src\reef\lang\cs\Org.Apache.REEF.Utilities\Diagnostics\Exceptions.cs:line 55
   at Org.Apache.REEF.Utilities.Diagnostics.Exceptions.Throw(Exception exception, Logger logger) in D:\src\reef\lang\cs\Org.Apache.REEF.Utilities\Diagnostics\Exceptions.cs:line 73
   at Org.Apache.REEF.Tang.Implementations.InjectionPlan.InjectorImpl.InjectFromPlan(InjectionPlan plan) in D:\src\reef\lang\cs\Org.Apache.REEF.Tang\Implementations\InjectionPlan\InjectorImpl.cs:line 188
   at Org.Apache.REEF.Tang.Implementations.InjectionPlan.InjectorImpl.InjectFromPlan(InjectionPlan plan) in D:\src\reef\lang\cs\Org.Apache.REEF.Tang\Implementations\InjectionPlan\InjectorImpl.cs:line 198
   at Org.Apache.REEF.Tang.Implementations.InjectionPlan.InjectorImpl.InjectFromPlan(InjectionPlan plan) in D:\src\reef\lang\cs\Org.Apache.REEF.Tang\Implementations\InjectionPlan\InjectorImpl.cs:line 198
   at Org.Apache.REEF.Tang.Implementations.InjectionPlan.InjectorImpl.InjectFromPlan(InjectionPlan plan) in D:\src\reef\lang\cs\Org.Apache.REEF.Tang\Implementations\InjectionPlan\InjectorImpl.cs:line 146
   at Org.Apache.REEF.Tang.Implementations.InjectionPlan.InjectorImpl.InjectFromPlan(InjectionPlan plan) in D:\src\reef\lang\cs\Org.Apache.REEF.Tang\Implementations\InjectionPlan\InjectorImpl.cs:line 198
   at Org.Apache.REEF.Tang.Implementations.InjectionPlan.InjectorImpl.InjectFromPlan(InjectionPlan plan) in D:\src\reef\lang\cs\Org.Apache.REEF.Tang\Implementations\InjectionPlan\InjectorImpl.cs:line 146
   at Org.Apache.REEF.Tang.Implementations.InjectionPlan.InjectorImpl.InjectFromPlan(InjectionPlan plan) in D:\src\reef\lang\cs\Org.Apache.REEF.Tang\Implementations\InjectionPlan\InjectorImpl.cs:line 198
   at Org.Apache.REEF.Tang.Implementations.InjectionPlan.InjectorImpl.GetInstance(INode node) in D:\src\reef\lang\cs\Org.Apache.REEF.Tang\Implementations\InjectionPlan\InjectorImpl.cs:line 781
   at Org.Apache.REEF.Tang.Implementations.InjectionPlan.InjectorImpl.GetInstance(String clazz) in D:\src\reef\lang\cs\Org.Apache.REEF.Tang\Implementations\InjectionPlan\InjectorImpl.cs:line 797
   at Org.Apache.REEF.Tang.Implementations.InjectionPlan.InjectorImpl.GetInstance[T]() in D:\src\reef\lang\cs\Org.Apache.REEF.Tang\Implementations\InjectionPlan\InjectorImpl.cs:line 764
   at Org.Apache.REEF.Tests.Functional.Bridge.TestSecurityToken.TestRun(IConfiguration config) in D:\src\reef\lang\cs\Org.Apache.REEF.Tests\Functional\Bridge\TestSecurityToken.cs:line 105
   at Org.Apache.REEF.Tests.Functional.Bridge.TestSecurityToken.TestSetOneSecurityToken() in D:\src\reef\lang\cs\Org.Apache.REEF.Tests\Functional\Bridge\TestSecurityToken.cs:line 94
----- Inner Stack Trace -----
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.ConstructorInfo.Invoke(Object[] parameters)
   at Org.Apache.REEF.Tang.Implementations.InjectionPlan.InjectorImpl.InjectFromPlan(InjectionPlan plan) in D:\src\reef\lang\cs\Org.Apache.REEF.Tang\Implementations\InjectionPlan\InjectorImpl.cs:line 164
----- Inner Stack Trace -----
   at Org.Apache.REEF.Utilities.Runtime.Yarn.YarnConfiguration..ctor(String hadoopConfDir, String yarnConfigFileName, Nullable`1 useHttps) in D:\src\reef\lang\cs\Org.Apache.REEF.Utilities\Runtime\Yarn\YarnConfiguration.cs:line 103
   at Org.Apache.REEF.Utilities.Runtime.Yarn.YarnConfiguration.GetConfiguration(String hadoopConfDir, String yarnConfigFileName, Nullable`1 useHttps) in D:\src\reef\lang\cs\Org.Apache.REEF.Utilities\Runtime\Yarn\YarnConfiguration.cs:line 82
   at Org.Apache.REEF.Client.Yarn.RestClient.YarnConfigurationUrlProvider..ctor(String hadoopConfigDir, Boolean useHttps) in D:\src\reef\lang\cs\Org.Apache.REEF.Client\YARN\RestClient\YarnConfigurationUrlProvider.cs:line 70
Result Message:	
Org.Apache.REEF.Tang.Exceptions.InjectionException : Could not invoke constructor: new Org.Apache.REEF.Client.Yarn.RestClient.YarnConfigurationUrlProvider(System.String Org.Apache.REEF.Client.Yarn.RestClient.YarnConfigurationUrlProvider+HadoopConfigurationDirectory =  , System.Boolean Org.Apache.REEF.Client.Yarn.RestClient.YarnConfigurationUrlProvider+UseHttpsForYarnCommunication = False)
---- System.Reflection.TargetInvocationException : Exception has been thrown by the target of an invocation.
-------- System.ArgumentException :  is not configured or does not exist.
```

```
Test Name:	Org.Apache.REEF.Tests.Functional.Failure.TestEvaluatorWithActiveContextDelayedPoison.TestPoisonedActiveContextHandlerWithDelay
Test FullName:	Org.Apache.REEF.Tests.Functional.Failure.TestEvaluatorWithActiveContextDelayedPoison.TestPoisonedActiveContextHandlerWithDelay
Test Source:	D:\src\reef\lang\cs\Org.Apache.REEF.Tests\Functional\Failure\TestEvaluatorWithActiveContextDelayedPoison.cs : line 41
Test Outcome:	Failed
Test Duration:	0:00:11.209

Result StackTrace:	
at Org.Apache.REEF.Tests.Functional.ReefFunctionalTest.ValidateMessageSuccessfullyLogged(IEnumerable`1 messages, String subfolder, String fileName, String testFolder, Int32 numberOfOccurrences) in D:\src\reef\lang\cs\Org.Apache.REEF.Tests\Functional\ReefFunctionalTest.cs:line 234
   at Org.Apache.REEF.Tests.Functional.ReefFunctionalTest.ValidateMessageSuccessfullyLoggedForDriver(String message, String testFolder, Int32 numberOfOccurrences) in D:\src\reef\lang\cs\Org.Apache.REEF.Tests\Functional\ReefFunctionalTest.cs:line 201
   at Org.Apache.REEF.Tests.Functional.Failure.TestEvaluatorWithActiveContextDelayedPoison.TestPoisonedActiveContextHandlerWithDelay() in D:\src\reef\lang\cs\Org.Apache.REEF.Tests\Functional\Failure\TestEvaluatorWithActiveContextDelayedPoison.cs:line 44
Result Message:	
Expected number of message "I have seen a failed evaluator with correct failed context and no task." occurrences 1 differs from actual 0
Expected: True
Actual:   False
```

**Comment by jwang98052** [comment]
@markusweimer I got same test failures in master. Can you try master as well?

**Comment by markusweimer** [comment]
Indeed. I filled them as 

  * https://issues.apache.org/jira/browse/REEF-1933
  * https://issues.apache.org/jira/browse/REEF-1932
  * https://issues.apache.org/jira/browse/REEF-1931

How shall we proceed?

**Comment by jwang98052** [comment]
Those are Yarn tests. I have tried other yarn tests in cluster with the change and they are all passed. I don't think the change in this PL will cause those test failures. I can run them again on Yarn. If pass, will resolve those JIRA.

**Comment by markusweimer** [comment]
> Those are Yarn tests. 

Ah, OK. How do I exclude them from my local test runs?

Anyway, I will proceed with merging this change.

**Pull request closed without merging**
