### PR TITLE
[REEF-1509] Fix broken links to the talks page

### PR DESCRIPTION
**Pull request by wonook**
This PR:

- Fixes the broken links to the talks page of our website

JIRA: [REEF-1509](https://issues.apache.org/jira/browse/REEF-1509)
closes

### CODE REVIEW

**Comment by wonook** [comment]
I'm unsure about the deployment process for the site though. Please verify
Thanks! 😄

**Comment by yunseong** [comment]
@wonook Thanks for the fix! I've checked that all the links point to the right place. I'll try to publish the website with the changes.

**Comment by tcNickolas** [comment]
@yunseong Please merge this pull request first before publishing the website. We only publish website from our master branch to make sure that our website might be lagging behind master but not the other way around.

**Comment by yunseong** [comment]
@tcNickolas Thanks a lot for reminding me! I'll merge this PR first.

**Pull request closed without merging**
