### PR TITLE
[REEF-1115] Increase maximum depth of package name of Tint and fix example images

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
This PR resolves the following things:
  * Increase the minimum depth of package name in `Tint.java`
    to adapt to the change of package prefix from `com.microsoft`
    to `org.apache.reef`.
  * Replace `com.microsoft` with `org.apache.reef` in `tangdoc.png`
    and `tooltip.png`.

JIRA:
  [REEF-1115](https://issues.apache.org/jira/browse/REEF-1115)

Pull Request:
  This closes #

### CODE REVIEW

**Comment by tcNickolas** [comment]
Do we need to increase the size of the images? I'm not sure how github resizes them when displaying README.md, they might not scale.

**Comment by dongjoon-hyun** [comment]
You can see that on my PR branch.

https://github.com/dongjoon-hyun/reef/tree/REEF-1115/lang/java/reef-tang

**Comment by tcNickolas** [comment]
Larger images scale fine.
Is Comic Sans (if I identify the font in the images correctly) a good choice for documentation?

**Comment by markusweimer** [comment]
> Is Comic Sans (if I identify the font in the images correctly) a good choice for documentation?

Well, it is fun :-) But more seriously speaking, Helvetica or such would be more appropriate.

**Comment by dongjoon-hyun** [comment]
It's just due to the following `Tang Tint`'s current logic, do you want to change that into `Helvetica` in this issue? No problem to do that. :)
```
out.println("body { font-family: 'Segoe UI', 'Comic Sans MS'; font-size:12pt; font-weight: 200; " +
            "margin: 1em; column-count: 2; }");
```

**Comment by tcNickolas** [comment]
Yes, I think it would be better to change the font to something more serious. After all, we've graduated from the incubator already ;-)

Also, the font in the code screenshot looks a bit weird too; could you make it something monospaced, like the font used in the previous version of the screenshot?

**Comment by dongjoon-hyun** [comment]
I totally agree with you. But I'm not good at this kind of art or designing work. 
Could you choose the font name specifically for me? :)

**Comment by tcNickolas** [comment]
As Marcus suggested, Helvetica for Tint-generated page. For tooltip screenshot, whichever monospaced font your IDE has (mine has just "Monospaced" as a default, but it's not a font name)

**Comment by dongjoon-hyun** [comment]
For 'Tint' code, I will change the following line into `Helvetica` instead of `Comic Sans` as you specified.
```
out.println("body { font-family: 'Segoe UI', 'Comic Sans MS'; font-size:12pt; font-weight: 200; " +
            "margin: 1em; column-count: 2; }");
```

But, for tooltip screen, what is your IDE and what OS do you mean? I didn't change any of the default setting of `Eclipse IDE (Mars.1 Release 4.5.1)`. In fact, I installed Eclipse on my Mac just to capture this tooltip image since the original image came from Eclipse.

I can capture that after newly installing Eclipse IDE on Windows 10. Do you think that is okay for you? I'm not sure what font will be, but I guess it will be closer to your environment.

Fonts or designs are always controversial. I didn't expect that I need to change the existing font of `Tint` code. :)

**Comment by dongjoon-hyun** [comment]
I'm still working on this. I'll let you know later.

**Comment by dongjoon-hyun** [comment]
@tcNickolas . I finished updating and checking now. You can see the change here.

https://github.com/dongjoon-hyun/reef/blob/3ee72a57cbf5034355ae853a73036293dd3be3ec/lang/java/reef-tang/README.md

`README.md` is slightly updated, too. Please look at that too. If that is not proper, please let me know.

**Comment by tcNickolas** [comment]
Looks good, I'll merge

**Comment by dongjoon-hyun** [comment]
Thank you, @tcNickolas !

**Pull request closed without merging**
