### PR TITLE
[REEF-1443] Find root cause of transient failure of testFailureRestar…

### PR DESCRIPTION
**Pull request by afchung**
…t in Jenkins

This addressed the issue by
  * Lowering the number of Evaluators to submit and restart to avoid hitting 1 minute timeout on Jenkins.

JIRA:
  [REEF-1443](https://issues.apache.org/jira/browse/REEF-1443)

### CODE REVIEW

**Comment by afchung** [comment]
**Please do not merge until Jenkins build passes consistently. I will be triggering the Jenkins build on this PR multiple times.** Thanks!

**Comment by jwang98052** [comment]
LGTM

**Comment by afchung** [comment]
This seems to pass consistently on Jenkins now. @jwang98052 would be great if you can merge. Thanks!

**Comment by jwang98052** [comment]
I will test and merge.

**Pull request closed without merging**
