### PR TITLE
[REEF-1540] Release 0.15.1

### PR DESCRIPTION
**Pull request by shulmanb**
This addresses the issue by
  *  Merging [REEF-1539] Fix memory leak in InteropUtil.cpp
  *  Merging [REEF-1528] Refactor dependency between yarn runtime and reef-webserver
  *  Merging [REEF-1529] Fixing reef-webserver for multi runtime

JIRA:
  [REEF-1540](https://issues.apache.org/jira/browse/REEF-1540)

### CODE REVIEW

**Comment by shulmanb** [comment]
@tcNickolas @motus Please take a look. It will probably be easier if I will push it myself to the branch-0.15.1.

**Comment by markusweimer** [comment]
This pull request is filled against `master`. Shouldn't it be filled against the release branch?

**Comment by shulmanb** [comment]
It should. Not sure how to do that, didn't see any knobs to specify that.

**Comment by shulmanb** [comment]
I will close this PR and create a new one against the correct branch.

**Comment by markusweimer** [comment]
There is [documentation](https://help.github.com/articles/creating-a-pull-request/) that suggests this is feasible.

**Pull request closed without merging**
