### PR TITLE
[REEF-1195] YARNClientConfiguration is broken for on-cluster YARN sub…

### PR DESCRIPTION
**Pull request by afchung**
…mission

This addressed the issue by
  * Bind IYarnRestClientCredential in ConfigurationModule.

JIRA:
  [REEF-1195](https://issues.apache.org/jira/browse/REEF-1195)

### CODE REVIEW

**Comment by afchung** [comment]
@anupam128 Please have a look at this PR. Thanks!

**Comment by anupam128** [comment]
+1 for merging.

**Comment by afchung** [comment]
Could one of the committers help with the merging? Thanks!

**Comment by markusweimer** [comment]
+1 on merging.

@afchung Feel free to do a self-merge, you have another committer's +1 :)

**Comment by markusweimer** [comment]
I'll merge this.

**Pull request closed without merging**
