### PR TITLE
[REEF-997] Fix spacing in C++ files

### PR DESCRIPTION
**Pull request by jieunparklee**
This addressed the issue by
  * Fixed the indentation in C++ files in REEF Bridge: tabs to double spaces

JIRA:
  [REEF-997](https://issues.apache.org/jira/browse/REEF-997)

### CODE REVIEW

**Comment by yunseong** [comment]
@afchung Could you take a look?

**Comment by markusweimer** [comment]
I'll test and merge.

**Comment by markusweimer** [comment]
Actually, there is a merge conflict with current `master`. @jieunparklee, can you please resolve and rebase?

**Comment by jieunparklee** [comment]
@markusweimer I couldn't find a conflict, though I did rebase again

**Comment by motus** [comment]
Hi @markusweimer and @jieunparklee, I've just merged and tested everything on my PC - there are no conflicts, and the build is fine. Do you want me to push nte new master to the main repo?

**Comment by markusweimer** [comment]
@motus +1 from me

**Comment by jieunparklee** [comment]
@motus Yes please. Thank you

**Comment by tcNickolas** [comment]
This change has been merged. @jieunparklee could you please close this PR?

**Comment by jieunparklee** [comment]
@tcNickolas Sure thanks!

**Pull request closed without merging**
