### PR TITLE
[REEF-1193] Move DOAP file into website/src/site/resources.

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
To avoid accidental removing `doap.rdf` in the future,
this explictly registers `doap.rdf` into website resources folder.
`website/publish.sh` will consider this as a web resource.

JIRA:
  [REEF-1193](https://issues.apache.org/jira/browse/REEF-1193)

Pull Request:
  This closes #

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
To reviewers, 
during end-to-end testing, `doap.rdf` file is recovered(uploaded into our sites correctly, http://reef.apache.org/doap.rdf).
Please check this PR using first two steps please; `cd website` and `mvn clean site:site`. Sorry for the inconvenience.

**Comment by tcNickolas** [comment]
Please also update `dev\update_website.py`

**Comment by dongjoon-hyun** [comment]
Thank you, @tcNickolas !  I updated that, too.

**Comment by tcNickolas** [comment]
I've checked that `mvn site:site` places `doap.rdf` in `website\target\staging\site`, and that `update_website.py` updates the file in the new location correctly. I'll merge

**Comment by dongjoon-hyun** [comment]
Thank you for reviewing and merging, @tcNickolas .

**Pull request closed without merging**
