### PR TITLE
[REEF-1221]  Remove hard coded evaluator.conf

### PR DESCRIPTION
**Pull request by jwang98052**
*Remove the config file from Example and tests
*Update Evaluator unit testing to simulate the config data on the fly instead of reading it from hard coded file
*Clean up the EvaluatorConfiguaration tests and remove EvaluatorTests
*Update Evaluator method comments

JIRA: [REEF-1221](https://issues.apache.org/jira/browse/REEF-1221)

This closes #

### CODE REVIEW

**Comment by markusweimer** [comment]
I will test

**Comment by markusweimer** [comment]
This has conflicts with `master`. @jwang98052, can you please rebase?

**Comment by jwang98052** [comment]
@markusweimer Synced with master.

**Comment by markusweimer** [comment]
Thanks, will test.

**Comment by markusweimer** [comment]
Tests pass locally, will merge.

**Pull request closed without merging**
