### PR TITLE
[REEF-1377] Move from C# Tasks to Threads to run user's Task

### PR DESCRIPTION
**Pull request by afchung**
This addressed the issue by
  * Moving from Tasks to Threads.
  * Switching the behavior of tests to reflect the move.

JIRA:
  [REEF-1377](https://issues.apache.org/jira/browse/REEF-1377)

### CODE REVIEW

**Comment by markusweimer** [comment]
I'll do a pass.

**Comment by markusweimer** [comment]
The locking in `TaskRuntime.RunTask` is confusing to me. It updates the task status, which triggers heartbeats, right? How do we make sure that no other, conflicting, heartbeats are sent at the same time?

**Comment by markusweimer** [comment]
Similarly, there is no locking around `TaskRuntime._currentStatus`, right?

**Comment by markusweimer** [comment]
LGTM, besides the questions I raised above. But those are equally valid for the code prior to this change, so I am +1 on merging.

**Comment by afchung** [comment]
@markusweimer Thanks for the concern! You're right, nothing is formally validated, but given what I know, `_currentStatus` and `HeartbeatManager` are thread safe objects. Provided that `HeartbeatManager` sends heartbeats sequentially, task status heartbeats are all sent based on the same `_currentStatus` object, and `_currentStatus` provides conflict checks when its state is updated, it does not seem likely that conflicting heartbeats regarding Tasks will be sent -- however, it is possible that heartbeats are sent with conflicting statuses in Evaluator and Task, as heartbeats regarding Evaluators are triggered from another thread.

This doesn't seem to pertain to this particular PR though.

**Comment by markusweimer** [comment]
> it does not seem likely that conflicting heartbeats regarding Tasks will be sent.

Famous last words :) We actually had that bug in java. 

> This doesn't seem to pertain to this particular PR though.

Agreed. Will test and merge.

**Pull request closed without merging**
