### PR TITLE
[REEF-1827] new Uri(path) in REEF.NET IO Returns Lowercase String

### PR DESCRIPTION
**Pull request by shouhengyi-microsoft**
This corresponds to [REEF-1827](https://issues.apache.org/jira/browse/REEF-1827). In the Org.Apache.REEF.IO.FileSystem.IFileSystem, we have many methods that are based on C#'s Uri. For example:
```
void CopyToLocal(Uri remoteFileUri, string localName);
void CreateDirectory(Uri directoryUri);
```
From the logging and my experiments, this converts path to lowercase characters. For example:
```
new Uri("hdfs://XYZ123/mypath/data.txt") // Returns "hdfs://xyz123/mypath/data.txt"
```
If we are interacting with hdfs, in the subsequent dfs command in Org.Apache.REEF.IO.FileSystem.Hadoop:
```
public void CopyToLocal(Uri remoteFileUri, string localName)
{
    _commandRunner.Run("dfs -get " + remoteFileUri + " " + localName);
}
```
this will fail, since hdfs is case-sensitive.

JIRA:
[REEF-1827](https://issues.apache.org/jira/browse/REEF-1827)

Pull request:
#1329

### CODE REVIEW

**Comment by shouhengyi-microsoft** [comment]
@motus 
I tried to create an unit test for this, but currently `_uriPrefix` in `HadoopFileSystem` is set to be `private`. The key to this test is to have an uppercase `_uriPrefix` to text if it is cast into lowercase. I can make `GetUriPrefix()` public for testing, but I don't think it is a good practice.

Do you have a better approach? Thanks!

**Comment by motus** [comment]
One option would be to create a file with a mixed-case name on HDFS, and see if we can access it correctly.  We have a bunch of unit tests that run on Hadoop when `REEF_TEST_YARN` environment variable is set, so it's OK to add one more.

**P.S.** Look at e.g. [UnmanagedAmTest](https://github.com/apache/reef/blob/master/lang/java/reef-runtime-yarn/src/test/java/org/apache/reef/runtime/yarn/driver/unmanaged/UnmanagedAmTest.java) to see how we use the JUnit `Assume` to run the test only when Hadoop testing is requested.

**Comment by motus** [comment]
Also, you can give `GetUriPrefix()` method package access, and make sure your unit tests are in the same package. I would probably have unit tests for both such configurations (i.e. using `GerUriPrefix()` and accessing HDFS)

**Comment by markusweimer** [comment]
@shouhengyi-microsoft @motus , what is the status of this PR? Still alive or should it be closed?

**Comment by shouhengyi-microsoft** [comment]
@markusweimer @motus mentioned that we can merged it from our last conversation. Any change needed?

**Comment by motus** [comment]
Oh @shouhengyi-microsoft I thought you planned to create a unit test for it?

**Comment by shouhengyi-microsoft** [comment]
@motus can you merge it as is? Thanks.

**Comment by motus** [comment]
OK I'll test and merge it now.

**Pull request closed without merging**
