### PR TITLE
[REEF-771] Initial attempt to have locality-aware scheduler for HDFS

### PR DESCRIPTION
**Pull request by shahankhatch**
Retrieves a FileSystem and obtains hostnames from submitted path's block locations.

### CODE REVIEW

**Comment by bgchun** [comment]
@shahankhatch Sorry for taking long. I was thinking when we use an existing evaluator we schedule a task based on locality. I.e., `SchedulerWithLocality.submitTask`  considers locality to choose which task to launch. In your implementation, you considered asking an evaluator based on the location of data. 

The PR fails the checks. Could you check if checkstyle and findbugs pass? 

@dafrista What would be better to implement?

**Comment by markusweimer** [comment]
What's the status of this PR? It hasn't been updated in a while.

**Comment by bgchun** [comment]
@dafrista Can you comment on this PR?

**Comment by dafrista** [comment]
@shahankhatch : I agree with @bgchun that with the current task scheduler model, considering locality on task submission probably makes sense.

This PR doesn't look ready. I think having a discussion about the design on JIRA before iterating further in code would be more productive. @shahankhatch, it would be great if you can lead-off the JIRA discussion with the design that you sketched out in this PR.

**Comment by markusweimer** [comment]
If this is indeed not ready to be merged and needs a design discussion, we should close the PR. @shahankhatch can you please do that?

**Comment by shahankhatch** [comment]
Closing this PR to have a design discussion on JIRA.

**Pull request closed without merging**
